// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type {
  PostApiV1AuthRegisterData,
  PostApiV1AuthRegisterResponses,
  PostApiV1AuthRegisterErrors,
  PostApiV1AuthLoginData,
  PostApiV1AuthLoginResponses,
  PostApiV1AuthLoginErrors,
  GetApiV1AuthMeData,
  GetApiV1AuthMeResponses,
  GetApiV1AuthMeErrors,
  PostApiV1AuthLogoutData,
  PostApiV1AuthLogoutResponses,
  PostApiV1AuthLogoutErrors,
  GetApiV1AuthSessionsData,
  GetApiV1AuthSessionsResponses,
  GetApiV1AuthSessionsErrors,
  DeleteApiV1AuthSessionsByIdData,
  DeleteApiV1AuthSessionsByIdResponses,
  DeleteApiV1AuthSessionsByIdErrors,
  PostApiV1AuthSessionsRevokeAllData,
  PostApiV1AuthSessionsRevokeAllResponses,
  PostApiV1AuthSessionsRevokeAllErrors,
  GetApiV1EventsData,
  GetApiV1EventsResponses,
  GetApiV1EventsErrors,
  PostApiV1EventsData,
  PostApiV1EventsResponses,
  PostApiV1EventsErrors,
  GetApiV1EventsByEventIdData,
  GetApiV1EventsByEventIdResponses,
  GetApiV1EventsByEventIdErrors,
  GetApiV1EventsByEventIdStatsData,
  GetApiV1EventsByEventIdStatsResponses,
  GetApiV1EventsByEventIdStatsErrors,
  GetApiV1EventsByEventIdMembersData,
  GetApiV1EventsByEventIdMembersResponses,
  GetApiV1EventsByEventIdMembersErrors,
  PostApiV1EventsByEventIdMembersData,
  PostApiV1EventsByEventIdMembersResponses,
  PostApiV1EventsByEventIdMembersErrors,
  DeleteApiV1EventsByEventIdMembersByUserIdData,
  DeleteApiV1EventsByEventIdMembersByUserIdResponses,
  DeleteApiV1EventsByEventIdMembersByUserIdErrors,
  GetApiV1EventsByEventIdAuditData,
  GetApiV1EventsByEventIdAuditResponses,
  GetApiV1EventsByEventIdAuditErrors,
  PostApiV1EventsByEventIdPhotosUploadIntentData,
  PostApiV1EventsByEventIdPhotosUploadIntentResponses,
  PostApiV1EventsByEventIdPhotosUploadIntentErrors,
  PostApiV1EventsByEventIdPhotosConfirmData,
  PostApiV1EventsByEventIdPhotosConfirmResponses,
  PostApiV1EventsByEventIdPhotosConfirmErrors,
  GetApiV1EventsByEventIdPhotosData,
  GetApiV1EventsByEventIdPhotosResponses,
  GetApiV1EventsByEventIdPhotosErrors,
  PostApiV1EventsByEventIdPhotosSelectData,
  PostApiV1EventsByEventIdPhotosSelectResponses,
  PostApiV1EventsByEventIdPhotosSelectErrors,
  DeleteApiV1PhotosByPhotoIdData,
  DeleteApiV1PhotosByPhotoIdResponses,
  DeleteApiV1PhotosByPhotoIdErrors,
  PatchApiV1PhotosByPhotoIdData,
  PatchApiV1PhotosByPhotoIdResponses,
  PatchApiV1PhotosByPhotoIdErrors,
  GetApiV1EventsByEventIdGalleriesData,
  GetApiV1EventsByEventIdGalleriesResponses,
  GetApiV1EventsByEventIdGalleriesErrors,
  PostApiV1EventsByEventIdGalleriesData,
  PostApiV1EventsByEventIdGalleriesResponses,
  PostApiV1EventsByEventIdGalleriesErrors,
  PostApiV1GalleriesByGalleryIdPublishData,
  PostApiV1GalleriesByGalleryIdPublishResponses,
  PostApiV1GalleriesByGalleryIdPublishErrors,
  PostApiV1GalleriesByGalleryIdUnpublishData,
  PostApiV1GalleriesByGalleryIdUnpublishResponses,
  PostApiV1GalleriesByGalleryIdUnpublishErrors,
  PostApiV1GalleriesByGalleryIdRotatePinData,
  PostApiV1GalleriesByGalleryIdRotatePinResponses,
  PostApiV1GalleriesByGalleryIdRotatePinErrors,
  DeleteApiV1GalleriesByGalleryIdData,
  DeleteApiV1GalleriesByGalleryIdResponses,
  DeleteApiV1GalleriesByGalleryIdErrors,
  PatchApiV1GalleriesByGalleryIdData,
  PatchApiV1GalleriesByGalleryIdResponses,
  PatchApiV1GalleriesByGalleryIdErrors,
  GetApiV1PublicGalleriesBySlugData,
  GetApiV1PublicGalleriesBySlugResponses,
  GetApiV1PublicGalleriesBySlugErrors,
  PostApiV1PublicGalleriesBySlugUnlockData,
  PostApiV1PublicGalleriesBySlugUnlockResponses,
  PostApiV1PublicGalleriesBySlugUnlockErrors,
  GetApiV1PublicGalleriesBySlugPhotosData,
  GetApiV1PublicGalleriesBySlugPhotosResponses,
  GetApiV1PublicGalleriesBySlugPhotosErrors,
  PostApiV1PublicGalleriesBySlugLockData,
  PostApiV1PublicGalleriesBySlugLockResponses,
  PostApiV1PublicGalleriesBySlugLockErrors,
  GetHealthData,
  GetHealthResponses,
  GetReadyData,
  GetReadyResponses,
  GetReadyErrors,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Create an account
 * Creates a platform account and signs it in. The first account you create is the Admin/Lead; team members are normally created through an event invite instead.
 */
export const postApiV1AuthRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1AuthRegisterData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1AuthRegisterResponses,
    PostApiV1AuthRegisterErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Sign in
 * Sets an httpOnly session cookie and a readable CSRF cookie. There is no bearer token: sessions are server-side rows, so signing out or being removed takes effect on the next request.
 */
export const postApiV1AuthLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1AuthLoginData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1AuthLoginResponses,
    PostApiV1AuthLoginErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Who am I
 * The frontend calls this once on boot to hydrate its auth store. Never cached.
 */
export const getApiV1AuthMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1AuthMeData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetApiV1AuthMeResponses, GetApiV1AuthMeErrors, ThrowOnError>({
    url: '/api/v1/auth/me',
    ...options,
  });
};

/**
 * Sign out
 * Deletes the session row. Not a flag, not a denylist -- the row.
 */
export const postApiV1AuthLogout = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1AuthLogoutData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostApiV1AuthLogoutResponses,
    PostApiV1AuthLogoutErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/logout',
    ...options,
  });
};

/**
 * List active sessions
 * Every device currently signed in as you. "current" marks the one making this request.
 */
export const getApiV1AuthSessions = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1AuthSessionsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiV1AuthSessionsResponses,
    GetApiV1AuthSessionsErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/sessions',
    ...options,
  });
};

/**
 * End one session
 */
export const deleteApiV1AuthSessionsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1AuthSessionsByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApiV1AuthSessionsByIdResponses,
    DeleteApiV1AuthSessionsByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/sessions/{id}',
    ...options,
  });
};

/**
 * Sign out everywhere else
 * Ends every session except the one making this request.
 */
export const postApiV1AuthSessionsRevokeAll = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1AuthSessionsRevokeAllData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostApiV1AuthSessionsRevokeAllResponses,
    PostApiV1AuthSessionsRevokeAllErrors,
    ThrowOnError
  >({
    url: '/api/v1/auth/sessions/revoke-all',
    ...options,
  });
};

/**
 * List my events
 * Only events you are a member of. Cursor-paginated, newest first.
 */
export const getApiV1Events = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1EventsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetApiV1EventsResponses, GetApiV1EventsErrors, ThrowOnError>({
    url: '/api/v1/events',
    ...options,
  });
};

/**
 * Create an event
 * The creator becomes its admin. Only platform admins can create events.
 */
export const postApiV1Events = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1EventsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1EventsResponses,
    PostApiV1EventsErrors,
    ThrowOnError
  >({
    url: '/api/v1/events',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get one event
 * A non-member gets 404, not 403: confirming an event exists is itself a leak.
 */
export const getApiV1EventsByEventId = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1EventsByEventIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiV1EventsByEventIdResponses,
    GetApiV1EventsByEventIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}',
    ...options,
  });
};

/**
 * Event totals
 * Counts live here, deliberately away from the paginated list endpoints, so a page fetch never pays for a COUNT(*) over 1,250 rows.
 */
export const getApiV1EventsByEventIdStats = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1EventsByEventIdStatsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiV1EventsByEventIdStatsResponses,
    GetApiV1EventsByEventIdStatsErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}/stats',
    ...options,
  });
};

/**
 * List team members
 */
export const getApiV1EventsByEventIdMembers = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1EventsByEventIdMembersData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiV1EventsByEventIdMembersResponses,
    GetApiV1EventsByEventIdMembersErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}/members',
    ...options,
  });
};

/**
 * Add a team member
 * Creates the account if the email is new and returns a one-time password for the demo. A real deployment would email an invite link instead; see the README.
 */
export const postApiV1EventsByEventIdMembers = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1EventsByEventIdMembersData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1EventsByEventIdMembersResponses,
    PostApiV1EventsByEventIdMembersErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}/members',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Remove a team member
 * Takes effect on their next request -- sessions are rows, so there is no token left to expire. The last admin cannot be removed.
 */
export const deleteApiV1EventsByEventIdMembersByUserId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1EventsByEventIdMembersByUserIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApiV1EventsByEventIdMembersByUserIdResponses,
    DeleteApiV1EventsByEventIdMembersByUserIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}/members/{userId}',
    ...options,
  });
};

/**
 * Audit log
 * Who did what on this event. Cursor-paginated, newest first.
 */
export const getApiV1EventsByEventIdAudit = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1EventsByEventIdAuditData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiV1EventsByEventIdAuditResponses,
    GetApiV1EventsByEventIdAuditErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}/audit',
    ...options,
  });
};

/**
 * Reserve upload slots
 * Validates the batch, reserves `pending` rows, and returns signed Supabase Storage PUT URLs. Bytes go straight to Supabase Storage and never pass through the API. Send the whole batch in one call, not one call per file. Files whose checksum already exists in this event come back under `duplicates` with no upload slot.
 */
export const postApiV1EventsByEventIdPhotosUploadIntent = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1EventsByEventIdPhotosUploadIntentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1EventsByEventIdPhotosUploadIntentResponses,
    PostApiV1EventsByEventIdPhotosUploadIntentErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}/photos/upload-intent',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Confirm uploaded files
 * Flips `pending` rows to `ready` and records dimensions and EXIF. Idempotent: a retried confirm after a flaky response changes nothing.
 */
export const postApiV1EventsByEventIdPhotosConfirm = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1EventsByEventIdPhotosConfirmData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1EventsByEventIdPhotosConfirmResponses,
    PostApiV1EventsByEventIdPhotosConfirmErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}/photos/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List photos in an event
 * Cursor-paginated. Pass `pageInfo.nextCursor` from the previous response as `cursor`. Cursors are signed and bound to the `sort` that minted them, so changing `sort` mid-walk returns 400 rather than a quietly wrong page. Filters compose into the keyset query without breaking the cursor.
 */
export const getApiV1EventsByEventIdPhotos = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1EventsByEventIdPhotosData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiV1EventsByEventIdPhotosResponses,
    GetApiV1EventsByEventIdPhotosErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}/photos',
    ...options,
  });
};

/**
 * Select or deselect photos in bulk
 * Curation is admin-only. Up to 500 ids per call.
 */
export const postApiV1EventsByEventIdPhotosSelect = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1EventsByEventIdPhotosSelectData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1EventsByEventIdPhotosSelectResponses,
    PostApiV1EventsByEventIdPhotosSelectErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}/photos/select',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete a photo
 * Soft delete, restorable for 30 days. The event lead can delete anything; an uploader can delete their own upload within 15 minutes of uploading it.
 */
export const deleteApiV1PhotosByPhotoId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1PhotosByPhotoIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApiV1PhotosByPhotoIdResponses,
    DeleteApiV1PhotosByPhotoIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/photos/{photoId}',
    ...options,
  });
};

/**
 * Edit one photo
 * The event lead can caption and select. An uploader can caption their own photo but never select it, because selection is a publishing decision.
 */
export const patchApiV1PhotosByPhotoId = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiV1PhotosByPhotoIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchApiV1PhotosByPhotoIdResponses,
    PatchApiV1PhotosByPhotoIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/photos/{photoId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List galleries for an event
 */
export const getApiV1EventsByEventIdGalleries = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1EventsByEventIdGalleriesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiV1EventsByEventIdGalleriesResponses,
    GetApiV1EventsByEventIdGalleriesErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}/galleries',
    ...options,
  });
};

/**
 * Create a gallery
 * Snapshots the chosen photos into the gallery and mints a URL and a 6-digit PIN. **The PIN is returned exactly once and is never readable again** -- store it or rotate it. The snapshot is deliberate: deselecting a photo afterwards does not change what the client already bookmarked.
 */
export const postApiV1EventsByEventIdGalleries = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1EventsByEventIdGalleriesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1EventsByEventIdGalleriesResponses,
    PostApiV1EventsByEventIdGalleriesErrors,
    ThrowOnError
  >({
    url: '/api/v1/events/{eventId}/galleries',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Publish a gallery
 * Makes the link work. Team members cannot do this.
 */
export const postApiV1GalleriesByGalleryIdPublish = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1GalleriesByGalleryIdPublishData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1GalleriesByGalleryIdPublishResponses,
    PostApiV1GalleriesByGalleryIdPublishErrors,
    ThrowOnError
  >({
    url: '/api/v1/galleries/{galleryId}/publish',
    ...options,
  });
};

/**
 * Unpublish a gallery
 * Takes the link offline and ends every customer session already inside it.
 */
export const postApiV1GalleriesByGalleryIdUnpublish = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1GalleriesByGalleryIdUnpublishData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1GalleriesByGalleryIdUnpublishResponses,
    PostApiV1GalleriesByGalleryIdUnpublishErrors,
    ThrowOnError
  >({
    url: '/api/v1/galleries/{galleryId}/unpublish',
    ...options,
  });
};

/**
 * Issue a new PIN
 * Mints a new PIN and **ends every customer session already inside the gallery**, so the old PIN and anyone using it are locked out immediately. Shown once.
 */
export const postApiV1GalleriesByGalleryIdRotatePin = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1GalleriesByGalleryIdRotatePinData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1GalleriesByGalleryIdRotatePinResponses,
    PostApiV1GalleriesByGalleryIdRotatePinErrors,
    ThrowOnError
  >({
    url: '/api/v1/galleries/{galleryId}/rotate-pin',
    ...options,
  });
};

/**
 * Delete a gallery
 */
export const deleteApiV1GalleriesByGalleryId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1GalleriesByGalleryIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApiV1GalleriesByGalleryIdResponses,
    DeleteApiV1GalleriesByGalleryIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/galleries/{galleryId}',
    ...options,
  });
};

/**
 * Edit a gallery
 */
export const patchApiV1GalleriesByGalleryId = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiV1GalleriesByGalleryIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchApiV1GalleriesByGalleryIdResponses,
    PatchApiV1GalleriesByGalleryIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/galleries/{galleryId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Preview a private gallery
 * Returns display-safe metadata only. Draft and unknown slugs are indistinguishable.
 */
export const getApiV1PublicGalleriesBySlug = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1PublicGalleriesBySlugData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiV1PublicGalleriesBySlugResponses,
    GetApiV1PublicGalleriesBySlugErrors,
    ThrowOnError
  >({
    url: '/api/v1/public/galleries/{slug}',
    ...options,
  });
};

/**
 * Unlock with the client PIN
 * Five failed attempts in 15 minutes are allowed; the sixth is rate-limited.
 */
export const postApiV1PublicGalleriesBySlugUnlock = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1PublicGalleriesBySlugUnlockData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1PublicGalleriesBySlugUnlockResponses,
    PostApiV1PublicGalleriesBySlugUnlockErrors,
    ThrowOnError
  >({
    url: '/api/v1/public/galleries/{slug}/unlock',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Browse the published snapshot
 */
export const getApiV1PublicGalleriesBySlugPhotos = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1PublicGalleriesBySlugPhotosData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiV1PublicGalleriesBySlugPhotosResponses,
    GetApiV1PublicGalleriesBySlugPhotosErrors,
    ThrowOnError
  >({
    url: '/api/v1/public/galleries/{slug}/photos',
    ...options,
  });
};

/**
 * Lock this gallery
 */
export const postApiV1PublicGalleriesBySlugLock = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1PublicGalleriesBySlugLockData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiV1PublicGalleriesBySlugLockResponses,
    PostApiV1PublicGalleriesBySlugLockErrors,
    ThrowOnError
  >({
    url: '/api/v1/public/galleries/{slug}/lock',
    ...options,
  });
};

/**
 * Liveness
 * The Worker is running. Says nothing about its dependencies.
 */
export const getHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetHealthResponses, unknown, ThrowOnError>({
    url: '/health',
    ...options,
  });
};

/**
 * Readiness
 * Supabase Postgres and Storage are both reachable. This is the one to point a monitor at.
 */
export const getReady = <ThrowOnError extends boolean = false>(
  options?: Options<GetReadyData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetReadyResponses, GetReadyErrors, ThrowOnError>({
    url: '/ready',
    ...options,
  });
};
