// This file is auto-generated by @hey-api/openapi-ts

export type PostApiV1AuthRegisterData = {
  body: {
    email: string;
    password: string;
    displayName: string;
  };
  path?: never;
  query?: never;
  url: '/api/v1/auth/register';
};

export type PostApiV1AuthRegisterErrors = {
  /**
   * That email is already registered.
   */
  409: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * The email or password failed validation.
   */
  422: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Too many attempts from this address.
   */
  429: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1AuthRegisterError = PostApiV1AuthRegisterErrors[keyof PostApiV1AuthRegisterErrors];

export type PostApiV1AuthRegisterResponses = {
  /**
   * Account created and signed in.
   */
  201: {
    user: {
      id: string;
      email: string;
      displayName: string;
      isPlatformAdmin: boolean;
      createdAt: number;
    };
    memberships: Array<{
      eventId: string;
      eventName: string;
      role: 'admin' | 'member';
    }>;
    csrfToken: string;
    sessionId: string;
  };
};

export type PostApiV1AuthRegisterResponse =
  PostApiV1AuthRegisterResponses[keyof PostApiV1AuthRegisterResponses];

export type PostApiV1AuthLoginData = {
  body: {
    email: string;
    password: string;
  };
  path?: never;
  query?: never;
  url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginErrors = {
  /**
   * Wrong email or password. The message is identical for both, on purpose.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Too many attempts from this address.
   */
  429: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1AuthLoginError = PostApiV1AuthLoginErrors[keyof PostApiV1AuthLoginErrors];

export type PostApiV1AuthLoginResponses = {
  /**
   * Signed in.
   */
  200: {
    user: {
      id: string;
      email: string;
      displayName: string;
      isPlatformAdmin: boolean;
      createdAt: number;
    };
    memberships: Array<{
      eventId: string;
      eventName: string;
      role: 'admin' | 'member';
    }>;
    csrfToken: string;
    sessionId: string;
  };
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type GetApiV1AuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/me';
};

export type GetApiV1AuthMeErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type GetApiV1AuthMeError = GetApiV1AuthMeErrors[keyof GetApiV1AuthMeErrors];

export type GetApiV1AuthMeResponses = {
  /**
   * The signed-in user and their event memberships.
   */
  200: {
    user: {
      id: string;
      email: string;
      displayName: string;
      isPlatformAdmin: boolean;
      createdAt: number;
    };
    memberships: Array<{
      eventId: string;
      eventName: string;
      role: 'admin' | 'member';
    }>;
    csrfToken: string;
    sessionId: string;
  };
};

export type GetApiV1AuthMeResponse = GetApiV1AuthMeResponses[keyof GetApiV1AuthMeResponses];

export type PostApiV1AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1AuthLogoutError = PostApiV1AuthLogoutErrors[keyof PostApiV1AuthLogoutErrors];

export type PostApiV1AuthLogoutResponses = {
  /**
   * Signed out.
   */
  204: void;
};

export type PostApiV1AuthLogoutResponse = PostApiV1AuthLogoutResponses[keyof PostApiV1AuthLogoutResponses];

export type GetApiV1AuthSessionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/sessions';
};

export type GetApiV1AuthSessionsErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type GetApiV1AuthSessionsError = GetApiV1AuthSessionsErrors[keyof GetApiV1AuthSessionsErrors];

export type GetApiV1AuthSessionsResponses = {
  /**
   * Active sessions, most recent first.
   */
  200: Array<{
    id: string;
    current: boolean;
    userAgent: string | null;
    createdAt: number;
    lastSeenAt: number;
    idleExpiresAt: number;
  }>;
};

export type GetApiV1AuthSessionsResponse = GetApiV1AuthSessionsResponses[keyof GetApiV1AuthSessionsResponses];

export type DeleteApiV1AuthSessionsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/auth/sessions/{id}';
};

export type DeleteApiV1AuthSessionsByIdErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such session.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type DeleteApiV1AuthSessionsByIdError =
  DeleteApiV1AuthSessionsByIdErrors[keyof DeleteApiV1AuthSessionsByIdErrors];

export type DeleteApiV1AuthSessionsByIdResponses = {
  /**
   * That session is gone.
   */
  204: void;
};

export type DeleteApiV1AuthSessionsByIdResponse =
  DeleteApiV1AuthSessionsByIdResponses[keyof DeleteApiV1AuthSessionsByIdResponses];

export type PostApiV1AuthSessionsRevokeAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/sessions/revoke-all';
};

export type PostApiV1AuthSessionsRevokeAllErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1AuthSessionsRevokeAllError =
  PostApiV1AuthSessionsRevokeAllErrors[keyof PostApiV1AuthSessionsRevokeAllErrors];

export type PostApiV1AuthSessionsRevokeAllResponses = {
  /**
   * How many sessions ended.
   */
  200: {
    revoked: number;
  };
};

export type PostApiV1AuthSessionsRevokeAllResponse =
  PostApiV1AuthSessionsRevokeAllResponses[keyof PostApiV1AuthSessionsRevokeAllResponses];

export type GetApiV1EventsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    cursor?: string;
  };
  url: '/api/v1/events';
};

export type GetApiV1EventsErrors = {
  /**
   * The cursor is malformed, tampered with, or was issued for a different sort order.
   */
  400: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * A query parameter failed validation.
   */
  422: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type GetApiV1EventsError = GetApiV1EventsErrors[keyof GetApiV1EventsErrors];

export type GetApiV1EventsResponses = {
  /**
   * A page of events.
   */
  200: {
    data: Array<{
      id: string;
      name: string;
      description: string | null;
      eventDate: number | null;
      ownerId: string;
      status: 'active' | 'archived';
      role: 'admin' | 'member';
      createdAt: number;
      updatedAt: number;
    }>;
    pageInfo: {
      nextCursor: string | null;
      prevCursor: string | null;
      hasNextPage: boolean;
      hasPrevPage: boolean;
      limit: number;
    };
  };
};

export type GetApiV1EventsResponse = GetApiV1EventsResponses[keyof GetApiV1EventsResponses];

export type PostApiV1EventsData = {
  body: {
    name: string;
    description?: string;
    eventDate?: number;
  };
  path?: never;
  query?: never;
  url: '/api/v1/events';
};

export type PostApiV1EventsErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Validation failed.
   */
  422: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1EventsError = PostApiV1EventsErrors[keyof PostApiV1EventsErrors];

export type PostApiV1EventsResponses = {
  /**
   * Created.
   */
  201: {
    id: string;
    name: string;
    description: string | null;
    eventDate: number | null;
    ownerId: string;
    status: 'active' | 'archived';
    role: 'admin' | 'member';
    createdAt: number;
    updatedAt: number;
  };
};

export type PostApiV1EventsResponse = PostApiV1EventsResponses[keyof PostApiV1EventsResponses];

export type GetApiV1EventsByEventIdData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/v1/events/{eventId}';
};

export type GetApiV1EventsByEventIdErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such event, or not yours.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type GetApiV1EventsByEventIdError = GetApiV1EventsByEventIdErrors[keyof GetApiV1EventsByEventIdErrors];

export type GetApiV1EventsByEventIdResponses = {
  /**
   * The event.
   */
  200: {
    id: string;
    name: string;
    description: string | null;
    eventDate: number | null;
    ownerId: string;
    status: 'active' | 'archived';
    role: 'admin' | 'member';
    createdAt: number;
    updatedAt: number;
  };
};

export type GetApiV1EventsByEventIdResponse =
  GetApiV1EventsByEventIdResponses[keyof GetApiV1EventsByEventIdResponses];

export type GetApiV1EventsByEventIdStatsData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/v1/events/{eventId}/stats';
};

export type GetApiV1EventsByEventIdStatsErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such event.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type GetApiV1EventsByEventIdStatsError =
  GetApiV1EventsByEventIdStatsErrors[keyof GetApiV1EventsByEventIdStatsErrors];

export type GetApiV1EventsByEventIdStatsResponses = {
  /**
   * Totals for the event.
   */
  200: {
    totalPhotos: number;
    readyPhotos: number;
    selectedPhotos: number;
    storageBytes: number;
    galleries: number;
    uploaders: Array<{
      userId: string;
      displayName: string;
      count: number;
    }>;
  };
};

export type GetApiV1EventsByEventIdStatsResponse =
  GetApiV1EventsByEventIdStatsResponses[keyof GetApiV1EventsByEventIdStatsResponses];

export type GetApiV1EventsByEventIdMembersData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: {
    limit?: number;
    cursor?: string;
  };
  url: '/api/v1/events/{eventId}/members';
};

export type GetApiV1EventsByEventIdMembersErrors = {
  /**
   * The cursor is malformed, tampered with, or was issued for a different sort order.
   */
  400: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * A query parameter failed validation.
   */
  422: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type GetApiV1EventsByEventIdMembersError =
  GetApiV1EventsByEventIdMembersErrors[keyof GetApiV1EventsByEventIdMembersErrors];

export type GetApiV1EventsByEventIdMembersResponses = {
  /**
   * A page of members.
   */
  200: {
    data: Array<{
      userId: string;
      email: string;
      displayName: string;
      role: 'admin' | 'member';
      addedAt: number;
      photoCount: number;
    }>;
    pageInfo: {
      nextCursor: string | null;
      prevCursor: string | null;
      hasNextPage: boolean;
      hasPrevPage: boolean;
      limit: number;
    };
  };
};

export type GetApiV1EventsByEventIdMembersResponse =
  GetApiV1EventsByEventIdMembersResponses[keyof GetApiV1EventsByEventIdMembersResponses];

export type PostApiV1EventsByEventIdMembersData = {
  body: {
    email: string;
    role: 'admin' | 'member';
    displayName?: string;
  };
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/v1/events/{eventId}/members';
};

export type PostApiV1EventsByEventIdMembersErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such event.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Already a member of this event.
   */
  409: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1EventsByEventIdMembersError =
  PostApiV1EventsByEventIdMembersErrors[keyof PostApiV1EventsByEventIdMembersErrors];

export type PostApiV1EventsByEventIdMembersResponses = {
  /**
   * Added. A temporary password appears only when a new account was created.
   */
  201: {
    userId: string;
    email: string;
    displayName: string;
    role: 'admin' | 'member';
    addedAt: number;
    photoCount: number;
    temporaryPassword?: string;
  };
};

export type PostApiV1EventsByEventIdMembersResponse =
  PostApiV1EventsByEventIdMembersResponses[keyof PostApiV1EventsByEventIdMembersResponses];

export type DeleteApiV1EventsByEventIdMembersByUserIdData = {
  body?: never;
  path: {
    eventId: string;
    userId: string;
  };
  query?: never;
  url: '/api/v1/events/{eventId}/members/{userId}';
};

export type DeleteApiV1EventsByEventIdMembersByUserIdErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Not a member of this event.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * That is the last admin on this event.
   */
  409: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type DeleteApiV1EventsByEventIdMembersByUserIdError =
  DeleteApiV1EventsByEventIdMembersByUserIdErrors[keyof DeleteApiV1EventsByEventIdMembersByUserIdErrors];

export type DeleteApiV1EventsByEventIdMembersByUserIdResponses = {
  /**
   * Removed.
   */
  204: void;
};

export type DeleteApiV1EventsByEventIdMembersByUserIdResponse =
  DeleteApiV1EventsByEventIdMembersByUserIdResponses[keyof DeleteApiV1EventsByEventIdMembersByUserIdResponses];

export type GetApiV1EventsByEventIdAuditData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: {
    limit?: number;
    cursor?: string;
  };
  url: '/api/v1/events/{eventId}/audit';
};

export type GetApiV1EventsByEventIdAuditErrors = {
  /**
   * The cursor is malformed, tampered with, or was issued for a different sort order.
   */
  400: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * A query parameter failed validation.
   */
  422: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type GetApiV1EventsByEventIdAuditError =
  GetApiV1EventsByEventIdAuditErrors[keyof GetApiV1EventsByEventIdAuditErrors];

export type GetApiV1EventsByEventIdAuditResponses = {
  /**
   * A page of audit entries.
   */
  200: {
    data: Array<{
      id: string;
      actorName: string | null;
      action: string;
      targetType: string | null;
      targetId: string | null;
      metadata: {
        [key: string]: unknown;
      } | null;
      createdAt: number;
    }>;
    pageInfo: {
      nextCursor: string | null;
      prevCursor: string | null;
      hasNextPage: boolean;
      hasPrevPage: boolean;
      limit: number;
    };
  };
};

export type GetApiV1EventsByEventIdAuditResponse =
  GetApiV1EventsByEventIdAuditResponses[keyof GetApiV1EventsByEventIdAuditResponses];

export type PostApiV1EventsByEventIdPhotosUploadIntentData = {
  body: {
    files: Array<{
      filename: string;
      contentType: 'image/jpeg' | 'image/png' | 'image/webp' | 'image/avif';
      fileSize: number;
      checksum?: string;
    }>;
  };
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/v1/events/{eventId}/photos/upload-intent';
};

export type PostApiV1EventsByEventIdPhotosUploadIntentErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such event.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * A file exceeds the 25 MB limit.
   */
  413: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Unsupported image type.
   */
  415: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * The manifest failed validation.
   */
  422: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1EventsByEventIdPhotosUploadIntentError =
  PostApiV1EventsByEventIdPhotosUploadIntentErrors[keyof PostApiV1EventsByEventIdPhotosUploadIntentErrors];

export type PostApiV1EventsByEventIdPhotosUploadIntentResponses = {
  /**
   * Upload slots, and any duplicates that were skipped.
   */
  200: {
    uploads: Array<{
      photoId: string;
      filename: string;
      uploadUrl: string;
      storageKey: string;
      expiresAt: number;
    }>;
    duplicates: Array<{
      filename: string;
      existingPhotoId: string;
    }>;
  };
};

export type PostApiV1EventsByEventIdPhotosUploadIntentResponse =
  PostApiV1EventsByEventIdPhotosUploadIntentResponses[keyof PostApiV1EventsByEventIdPhotosUploadIntentResponses];

export type PostApiV1EventsByEventIdPhotosConfirmData = {
  body: {
    items: Array<{
      photoId: string;
      width?: number;
      height?: number;
      takenAt?: number;
      dominantColor?: string;
    }>;
  };
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/v1/events/{eventId}/photos/confirm';
};

export type PostApiV1EventsByEventIdPhotosConfirmErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such event.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1EventsByEventIdPhotosConfirmError =
  PostApiV1EventsByEventIdPhotosConfirmErrors[keyof PostApiV1EventsByEventIdPhotosConfirmErrors];

export type PostApiV1EventsByEventIdPhotosConfirmResponses = {
  /**
   * What became ready.
   */
  200: {
    confirmed: number;
    missing: Array<string>;
  };
};

export type PostApiV1EventsByEventIdPhotosConfirmResponse =
  PostApiV1EventsByEventIdPhotosConfirmResponses[keyof PostApiV1EventsByEventIdPhotosConfirmResponses];

export type GetApiV1EventsByEventIdPhotosData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: {
    limit?: number;
    cursor?: string;
    sort?: 'newest' | 'oldest' | 'filename' | 'size' | 'taken';
    search?: string;
    uploaderId?: string;
    selected?: 'true' | 'false';
    from?: number | null;
    to?: number | null;
  };
  url: '/api/v1/events/{eventId}/photos';
};

export type GetApiV1EventsByEventIdPhotosErrors = {
  /**
   * The cursor is malformed, tampered with, or was issued for a different sort order.
   */
  400: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such event.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * A query parameter failed validation.
   */
  422: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type GetApiV1EventsByEventIdPhotosError =
  GetApiV1EventsByEventIdPhotosErrors[keyof GetApiV1EventsByEventIdPhotosErrors];

export type GetApiV1EventsByEventIdPhotosResponses = {
  /**
   * A page of photos.
   */
  200: {
    data: Array<{
      id: string;
      eventId: string;
      uploadedBy: string;
      uploaderName?: string;
      filename: string;
      storageKey: string;
      contentType: string;
      fileSize: number;
      width: number | null;
      height: number | null;
      dominantColor: string | null;
      caption: string | null;
      takenAt: number | null;
      status: 'pending' | 'ready' | 'failed' | 'deleted';
      isSelected: boolean;
      createdAt: number;
    }>;
    pageInfo: {
      nextCursor: string | null;
      prevCursor: string | null;
      hasNextPage: boolean;
      hasPrevPage: boolean;
      limit: number;
    };
  };
};

export type GetApiV1EventsByEventIdPhotosResponse =
  GetApiV1EventsByEventIdPhotosResponses[keyof GetApiV1EventsByEventIdPhotosResponses];

export type PostApiV1EventsByEventIdPhotosSelectData = {
  body: {
    photoIds: Array<string>;
    selected: boolean;
  };
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/v1/events/{eventId}/photos/select';
};

export type PostApiV1EventsByEventIdPhotosSelectErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1EventsByEventIdPhotosSelectError =
  PostApiV1EventsByEventIdPhotosSelectErrors[keyof PostApiV1EventsByEventIdPhotosSelectErrors];

export type PostApiV1EventsByEventIdPhotosSelectResponses = {
  /**
   * How many changed.
   */
  200: {
    updated: number;
  };
};

export type PostApiV1EventsByEventIdPhotosSelectResponse =
  PostApiV1EventsByEventIdPhotosSelectResponses[keyof PostApiV1EventsByEventIdPhotosSelectResponses];

export type DeleteApiV1PhotosByPhotoIdData = {
  body?: never;
  path: {
    photoId: string;
  };
  query?: never;
  url: '/api/v1/photos/{photoId}';
};

export type DeleteApiV1PhotosByPhotoIdErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such photo.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type DeleteApiV1PhotosByPhotoIdError =
  DeleteApiV1PhotosByPhotoIdErrors[keyof DeleteApiV1PhotosByPhotoIdErrors];

export type DeleteApiV1PhotosByPhotoIdResponses = {
  /**
   * Deleted.
   */
  204: void;
};

export type DeleteApiV1PhotosByPhotoIdResponse =
  DeleteApiV1PhotosByPhotoIdResponses[keyof DeleteApiV1PhotosByPhotoIdResponses];

export type PatchApiV1PhotosByPhotoIdData = {
  body: {
    caption?: string | null;
    isSelected?: boolean;
  };
  path: {
    photoId: string;
  };
  query?: never;
  url: '/api/v1/photos/{photoId}';
};

export type PatchApiV1PhotosByPhotoIdErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such photo.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PatchApiV1PhotosByPhotoIdError =
  PatchApiV1PhotosByPhotoIdErrors[keyof PatchApiV1PhotosByPhotoIdErrors];

export type PatchApiV1PhotosByPhotoIdResponses = {
  /**
   * The updated photo.
   */
  200: {
    id: string;
    eventId: string;
    uploadedBy: string;
    uploaderName?: string;
    filename: string;
    storageKey: string;
    contentType: string;
    fileSize: number;
    width: number | null;
    height: number | null;
    dominantColor: string | null;
    caption: string | null;
    takenAt: number | null;
    status: 'pending' | 'ready' | 'failed' | 'deleted';
    isSelected: boolean;
    createdAt: number;
  };
};

export type PatchApiV1PhotosByPhotoIdResponse =
  PatchApiV1PhotosByPhotoIdResponses[keyof PatchApiV1PhotosByPhotoIdResponses];

export type GetApiV1EventsByEventIdGalleriesData = {
  body?: never;
  path: {
    eventId: string;
  };
  query?: {
    limit?: number;
    cursor?: string;
  };
  url: '/api/v1/events/{eventId}/galleries';
};

export type GetApiV1EventsByEventIdGalleriesErrors = {
  /**
   * The cursor is malformed, tampered with, or was issued for a different sort order.
   */
  400: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * A query parameter failed validation.
   */
  422: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type GetApiV1EventsByEventIdGalleriesError =
  GetApiV1EventsByEventIdGalleriesErrors[keyof GetApiV1EventsByEventIdGalleriesErrors];

export type GetApiV1EventsByEventIdGalleriesResponses = {
  /**
   * A page of galleries.
   */
  200: {
    data: Array<{
      id: string;
      eventId: string;
      slug: string;
      title: string;
      status: 'draft' | 'published' | 'unpublished';
      photoCount: number;
      allowDownload: boolean;
      expiresAt: number | null;
      publishedAt: number | null;
      viewCount: number;
      lastViewedAt: number | null;
      createdAt: number;
    }>;
    pageInfo: {
      nextCursor: string | null;
      prevCursor: string | null;
      hasNextPage: boolean;
      hasPrevPage: boolean;
      limit: number;
    };
  };
};

export type GetApiV1EventsByEventIdGalleriesResponse =
  GetApiV1EventsByEventIdGalleriesResponses[keyof GetApiV1EventsByEventIdGalleriesResponses];

export type PostApiV1EventsByEventIdGalleriesData = {
  body: {
    title: string;
    photoIds?: Array<string>;
    useSelected?: boolean;
    expiresAt?: number;
    allowDownload?: boolean;
    publish?: boolean;
  };
  path: {
    eventId: string;
  };
  query?: never;
  url: '/api/v1/events/{eventId}/galleries';
};

export type PostApiV1EventsByEventIdGalleriesErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such event.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No photos chosen, or validation failed.
   */
  422: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1EventsByEventIdGalleriesError =
  PostApiV1EventsByEventIdGalleriesErrors[keyof PostApiV1EventsByEventIdGalleriesErrors];

export type PostApiV1EventsByEventIdGalleriesResponses = {
  /**
   * Created. The PIN appears here and nowhere else.
   */
  201: {
    gallery: {
      id: string;
      eventId: string;
      slug: string;
      title: string;
      status: 'draft' | 'published' | 'unpublished';
      photoCount: number;
      allowDownload: boolean;
      expiresAt: number | null;
      publishedAt: number | null;
      viewCount: number;
      lastViewedAt: number | null;
      createdAt: number;
    };
    url: string;
    pin: string;
  };
};

export type PostApiV1EventsByEventIdGalleriesResponse =
  PostApiV1EventsByEventIdGalleriesResponses[keyof PostApiV1EventsByEventIdGalleriesResponses];

export type PostApiV1GalleriesByGalleryIdPublishData = {
  body?: never;
  path: {
    galleryId: string;
  };
  query?: never;
  url: '/api/v1/galleries/{galleryId}/publish';
};

export type PostApiV1GalleriesByGalleryIdPublishErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such gallery.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1GalleriesByGalleryIdPublishError =
  PostApiV1GalleriesByGalleryIdPublishErrors[keyof PostApiV1GalleriesByGalleryIdPublishErrors];

export type PostApiV1GalleriesByGalleryIdPublishResponses = {
  /**
   * The updated gallery.
   */
  200: {
    id: string;
    eventId: string;
    slug: string;
    title: string;
    status: 'draft' | 'published' | 'unpublished';
    photoCount: number;
    allowDownload: boolean;
    expiresAt: number | null;
    publishedAt: number | null;
    viewCount: number;
    lastViewedAt: number | null;
    createdAt: number;
  };
};

export type PostApiV1GalleriesByGalleryIdPublishResponse =
  PostApiV1GalleriesByGalleryIdPublishResponses[keyof PostApiV1GalleriesByGalleryIdPublishResponses];

export type PostApiV1GalleriesByGalleryIdUnpublishData = {
  body?: never;
  path: {
    galleryId: string;
  };
  query?: never;
  url: '/api/v1/galleries/{galleryId}/unpublish';
};

export type PostApiV1GalleriesByGalleryIdUnpublishErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such gallery.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1GalleriesByGalleryIdUnpublishError =
  PostApiV1GalleriesByGalleryIdUnpublishErrors[keyof PostApiV1GalleriesByGalleryIdUnpublishErrors];

export type PostApiV1GalleriesByGalleryIdUnpublishResponses = {
  /**
   * The updated gallery.
   */
  200: {
    id: string;
    eventId: string;
    slug: string;
    title: string;
    status: 'draft' | 'published' | 'unpublished';
    photoCount: number;
    allowDownload: boolean;
    expiresAt: number | null;
    publishedAt: number | null;
    viewCount: number;
    lastViewedAt: number | null;
    createdAt: number;
  };
};

export type PostApiV1GalleriesByGalleryIdUnpublishResponse =
  PostApiV1GalleriesByGalleryIdUnpublishResponses[keyof PostApiV1GalleriesByGalleryIdUnpublishResponses];

export type PostApiV1GalleriesByGalleryIdRotatePinData = {
  body?: never;
  path: {
    galleryId: string;
  };
  query?: never;
  url: '/api/v1/galleries/{galleryId}/rotate-pin';
};

export type PostApiV1GalleriesByGalleryIdRotatePinErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such gallery.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1GalleriesByGalleryIdRotatePinError =
  PostApiV1GalleriesByGalleryIdRotatePinErrors[keyof PostApiV1GalleriesByGalleryIdRotatePinErrors];

export type PostApiV1GalleriesByGalleryIdRotatePinResponses = {
  /**
   * The new PIN. This is the only time it is shown.
   */
  200: {
    pin: string;
  };
};

export type PostApiV1GalleriesByGalleryIdRotatePinResponse =
  PostApiV1GalleriesByGalleryIdRotatePinResponses[keyof PostApiV1GalleriesByGalleryIdRotatePinResponses];

export type DeleteApiV1GalleriesByGalleryIdData = {
  body?: never;
  path: {
    galleryId: string;
  };
  query?: never;
  url: '/api/v1/galleries/{galleryId}';
};

export type DeleteApiV1GalleriesByGalleryIdErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such gallery.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type DeleteApiV1GalleriesByGalleryIdError =
  DeleteApiV1GalleriesByGalleryIdErrors[keyof DeleteApiV1GalleriesByGalleryIdErrors];

export type DeleteApiV1GalleriesByGalleryIdResponses = {
  /**
   * Deleted.
   */
  204: void;
};

export type DeleteApiV1GalleriesByGalleryIdResponse =
  DeleteApiV1GalleriesByGalleryIdResponses[keyof DeleteApiV1GalleriesByGalleryIdResponses];

export type PatchApiV1GalleriesByGalleryIdData = {
  body: {
    title?: string;
    expiresAt?: number | null;
    allowDownload?: boolean;
    coverPhotoId?: string | null;
  };
  path: {
    galleryId: string;
  };
  query?: never;
  url: '/api/v1/galleries/{galleryId}';
};

export type PatchApiV1GalleriesByGalleryIdErrors = {
  /**
   * Not signed in, or the session was revoked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Signed in, but not allowed to do this.
   */
  403: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * No such gallery.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PatchApiV1GalleriesByGalleryIdError =
  PatchApiV1GalleriesByGalleryIdErrors[keyof PatchApiV1GalleriesByGalleryIdErrors];

export type PatchApiV1GalleriesByGalleryIdResponses = {
  /**
   * The updated gallery.
   */
  200: {
    id: string;
    eventId: string;
    slug: string;
    title: string;
    status: 'draft' | 'published' | 'unpublished';
    photoCount: number;
    allowDownload: boolean;
    expiresAt: number | null;
    publishedAt: number | null;
    viewCount: number;
    lastViewedAt: number | null;
    createdAt: number;
  };
};

export type PatchApiV1GalleriesByGalleryIdResponse =
  PatchApiV1GalleriesByGalleryIdResponses[keyof PatchApiV1GalleriesByGalleryIdResponses];

export type GetApiV1PublicGalleriesBySlugData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/v1/public/galleries/{slug}';
};

export type GetApiV1PublicGalleriesBySlugErrors = {
  /**
   * Unknown, draft, or unpublished. These intentionally look identical.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * The gallery expired.
   */
  410: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type GetApiV1PublicGalleriesBySlugError =
  GetApiV1PublicGalleriesBySlugErrors[keyof GetApiV1PublicGalleriesBySlugErrors];

export type GetApiV1PublicGalleriesBySlugResponses = {
  /**
   * Safe metadata for the PIN screen.
   */
  200: {
    title: string;
    photoCount: number;
    coverThumbUrl: string | null;
    allowDownload: boolean;
    expiresAt: number | null;
    unlocked: boolean;
  };
};

export type GetApiV1PublicGalleriesBySlugResponse =
  GetApiV1PublicGalleriesBySlugResponses[keyof GetApiV1PublicGalleriesBySlugResponses];

export type PostApiV1PublicGalleriesBySlugUnlockData = {
  body: {
    pin: string;
  };
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/v1/public/galleries/{slug}/unlock';
};

export type PostApiV1PublicGalleriesBySlugUnlockErrors = {
  /**
   * The PIN was wrong.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Unknown, draft, or unpublished.
   */
  404: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * The gallery expired.
   */
  410: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * The PIN is not six digits.
   */
  422: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Too many attempts. Includes Retry-After.
   */
  429: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1PublicGalleriesBySlugUnlockError =
  PostApiV1PublicGalleriesBySlugUnlockErrors[keyof PostApiV1PublicGalleriesBySlugUnlockErrors];

export type PostApiV1PublicGalleriesBySlugUnlockResponses = {
  /**
   * Unlocked. A gallery-specific, path-scoped cookie was set.
   */
  204: void;
};

export type PostApiV1PublicGalleriesBySlugUnlockResponse =
  PostApiV1PublicGalleriesBySlugUnlockResponses[keyof PostApiV1PublicGalleriesBySlugUnlockResponses];

export type GetApiV1PublicGalleriesBySlugPhotosData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: {
    limit?: number;
    cursor?: string;
  };
  url: '/api/v1/public/galleries/{slug}/photos';
};

export type GetApiV1PublicGalleriesBySlugPhotosErrors = {
  /**
   * The cursor is malformed, tampered with, or was issued for a different sort order.
   */
  400: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Enter the PIN again.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * Expired.
   */
  410: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
  /**
   * A query parameter failed validation.
   */
  422: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type GetApiV1PublicGalleriesBySlugPhotosError =
  GetApiV1PublicGalleriesBySlugPhotosErrors[keyof GetApiV1PublicGalleriesBySlugPhotosErrors];

export type GetApiV1PublicGalleriesBySlugPhotosResponses = {
  /**
   * A curated page.
   */
  200: {
    data: Array<{
      id: string;
      eventId: string;
      uploadedBy: string;
      uploaderName?: string;
      filename: string;
      storageKey: string;
      contentType: string;
      fileSize: number;
      width: number | null;
      height: number | null;
      dominantColor: string | null;
      caption: string | null;
      takenAt: number | null;
      status: 'pending' | 'ready' | 'failed' | 'deleted';
      isSelected: boolean;
      createdAt: number;
    }>;
    pageInfo: {
      nextCursor: string | null;
      prevCursor: string | null;
      hasNextPage: boolean;
      hasPrevPage: boolean;
      limit: number;
    };
  };
};

export type GetApiV1PublicGalleriesBySlugPhotosResponse =
  GetApiV1PublicGalleriesBySlugPhotosResponses[keyof GetApiV1PublicGalleriesBySlugPhotosResponses];

export type PostApiV1PublicGalleriesBySlugLockData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/api/v1/public/galleries/{slug}/lock';
};

export type PostApiV1PublicGalleriesBySlugLockErrors = {
  /**
   * Not unlocked.
   */
  401: {
    error: {
      code: string;
      message: string;
      details?: Array<{
        path: string;
        message: string;
      }>;
      requestId: string;
    };
  };
};

export type PostApiV1PublicGalleriesBySlugLockError =
  PostApiV1PublicGalleriesBySlugLockErrors[keyof PostApiV1PublicGalleriesBySlugLockErrors];

export type PostApiV1PublicGalleriesBySlugLockResponses = {
  /**
   * This gallery session ended.
   */
  204: void;
};

export type PostApiV1PublicGalleriesBySlugLockResponse =
  PostApiV1PublicGalleriesBySlugLockResponses[keyof PostApiV1PublicGalleriesBySlugLockResponses];

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type GetHealthResponses = {
  /**
   * Alive.
   */
  200: {
    status: 'ok';
  };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetReadyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/ready';
};

export type GetReadyErrors = {
  /**
   * Not ready.
   */
  503: {
    status: 'degraded';
    db: boolean;
    bucket: boolean;
  };
};

export type GetReadyError = GetReadyErrors[keyof GetReadyErrors];

export type GetReadyResponses = {
  /**
   * Ready.
   */
  200: {
    status: 'ready';
    db: boolean;
    bucket: boolean;
  };
};

export type GetReadyResponse = GetReadyResponses[keyof GetReadyResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
