// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zPostApiV1AuthRegisterData = z.object({
  email: z.string().email().max(254),
  password: z.string().min(10).max(200),
  displayName: z.string().min(1).max(80),
});

/**
 * Account created and signed in.
 */
export const zPostApiV1AuthRegisterResponse = z.object({
  user: z.object({
    id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
    email: z.string(),
    displayName: z.string(),
    isPlatformAdmin: z.boolean(),
    createdAt: z.number().int(),
  }),
  memberships: z.array(
    z.object({
      eventId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      eventName: z.string(),
      role: z.enum(['admin', 'member']),
    }),
  ),
  csrfToken: z.string(),
  sessionId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
});

export const zPostApiV1AuthLoginData = z.object({
  email: z.string().email().max(254),
  password: z.string().min(1).max(200),
});

/**
 * Signed in.
 */
export const zPostApiV1AuthLoginResponse = z.object({
  user: z.object({
    id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
    email: z.string(),
    displayName: z.string(),
    isPlatformAdmin: z.boolean(),
    createdAt: z.number().int(),
  }),
  memberships: z.array(
    z.object({
      eventId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      eventName: z.string(),
      role: z.enum(['admin', 'member']),
    }),
  ),
  csrfToken: z.string(),
  sessionId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
});

/**
 * The signed-in user and their event memberships.
 */
export const zGetApiV1AuthMeResponse = z.object({
  user: z.object({
    id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
    email: z.string(),
    displayName: z.string(),
    isPlatformAdmin: z.boolean(),
    createdAt: z.number().int(),
  }),
  memberships: z.array(
    z.object({
      eventId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      eventName: z.string(),
      role: z.enum(['admin', 'member']),
    }),
  ),
  csrfToken: z.string(),
  sessionId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
});

/**
 * Signed out.
 */
export const zPostApiV1AuthLogoutResponse = z.void();

/**
 * Active sessions, most recent first.
 */
export const zGetApiV1AuthSessionsResponse = z.array(
  z.object({
    id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
    current: z.boolean(),
    userAgent: z.union([z.string(), z.null()]),
    createdAt: z.number().int(),
    lastSeenAt: z.number().int(),
    idleExpiresAt: z.number().int(),
  }),
);

export const zDeleteApiV1AuthSessionsByIdParameterId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * That session is gone.
 */
export const zDeleteApiV1AuthSessionsByIdResponse = z.void();

/**
 * How many sessions ended.
 */
export const zPostApiV1AuthSessionsRevokeAllResponse = z.object({
  revoked: z.number().int(),
});

export const zGetApiV1EventsParameterLimit = z.number().int().gte(1).lte(100).default(24);

export const zGetApiV1EventsParameterCursor = z.string().max(512);

/**
 * A page of events.
 */
export const zGetApiV1EventsResponse = z.object({
  data: z.array(
    z.object({
      id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      name: z.string(),
      description: z.union([z.string(), z.null()]),
      eventDate: z.union([z.number().int(), z.null()]),
      ownerId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      status: z.enum(['active', 'archived']),
      role: z.enum(['admin', 'member']),
      createdAt: z.number().int(),
      updatedAt: z.number().int(),
    }),
  ),
  pageInfo: z.object({
    nextCursor: z.union([z.string(), z.null()]),
    prevCursor: z.union([z.string(), z.null()]),
    hasNextPage: z.boolean(),
    hasPrevPage: z.boolean(),
    limit: z.number().int(),
  }),
});

export const zPostApiV1EventsData = z.object({
  name: z.string().min(1).max(140),
  description: z.string().max(2000).optional(),
  eventDate: z.number().int().optional(),
});

/**
 * Created.
 */
export const zPostApiV1EventsResponse = z.object({
  id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  name: z.string(),
  description: z.union([z.string(), z.null()]),
  eventDate: z.union([z.number().int(), z.null()]),
  ownerId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  status: z.enum(['active', 'archived']),
  role: z.enum(['admin', 'member']),
  createdAt: z.number().int(),
  updatedAt: z.number().int(),
});

export const zGetApiV1EventsByEventIdParameterEventId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * The event.
 */
export const zGetApiV1EventsByEventIdResponse = z.object({
  id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  name: z.string(),
  description: z.union([z.string(), z.null()]),
  eventDate: z.union([z.number().int(), z.null()]),
  ownerId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  status: z.enum(['active', 'archived']),
  role: z.enum(['admin', 'member']),
  createdAt: z.number().int(),
  updatedAt: z.number().int(),
});

export const zGetApiV1EventsByEventIdStatsParameterEventId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * Totals for the event.
 */
export const zGetApiV1EventsByEventIdStatsResponse = z.object({
  totalPhotos: z.number().int(),
  readyPhotos: z.number().int(),
  selectedPhotos: z.number().int(),
  storageBytes: z.number().int(),
  galleries: z.number().int(),
  uploaders: z.array(
    z.object({
      userId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      displayName: z.string(),
      count: z.number().int(),
    }),
  ),
});

export const zGetApiV1EventsByEventIdMembersParameterEventId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

export const zGetApiV1EventsByEventIdMembersParameterLimit = z.number().int().gte(1).lte(100).default(24);

export const zGetApiV1EventsByEventIdMembersParameterCursor = z.string().max(512);

/**
 * A page of members.
 */
export const zGetApiV1EventsByEventIdMembersResponse = z.object({
  data: z.array(
    z.object({
      userId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      email: z.string(),
      displayName: z.string(),
      role: z.enum(['admin', 'member']),
      addedAt: z.number().int(),
      photoCount: z.number().int(),
    }),
  ),
  pageInfo: z.object({
    nextCursor: z.union([z.string(), z.null()]),
    prevCursor: z.union([z.string(), z.null()]),
    hasNextPage: z.boolean(),
    hasPrevPage: z.boolean(),
    limit: z.number().int(),
  }),
});

export const zPostApiV1EventsByEventIdMembersData = z.object({
  email: z.string().email().max(254),
  role: z.enum(['admin', 'member']),
  displayName: z.string().max(80).optional(),
});

export const zPostApiV1EventsByEventIdMembersParameterEventId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * Added. A temporary password appears only when a new account was created.
 */
export const zPostApiV1EventsByEventIdMembersResponse = z.object({
  userId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  email: z.string(),
  displayName: z.string(),
  role: z.enum(['admin', 'member']),
  addedAt: z.number().int(),
  photoCount: z.number().int(),
  temporaryPassword: z.string().optional(),
});

export const zDeleteApiV1EventsByEventIdMembersByUserIdParameterEventId = z
  .string()
  .regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

export const zDeleteApiV1EventsByEventIdMembersByUserIdParameterUserId = z
  .string()
  .regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * Removed.
 */
export const zDeleteApiV1EventsByEventIdMembersByUserIdResponse = z.void();

export const zGetApiV1EventsByEventIdAuditParameterEventId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

export const zGetApiV1EventsByEventIdAuditParameterLimit = z.number().int().gte(1).lte(100).default(24);

export const zGetApiV1EventsByEventIdAuditParameterCursor = z.string().max(512);

/**
 * A page of audit entries.
 */
export const zGetApiV1EventsByEventIdAuditResponse = z.object({
  data: z.array(
    z.object({
      id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      actorName: z.union([z.string(), z.null()]),
      action: z.string(),
      targetType: z.union([z.string(), z.null()]),
      targetId: z.union([z.string(), z.null()]),
      metadata: z.union([z.object({}), z.null()]),
      createdAt: z.number().int(),
    }),
  ),
  pageInfo: z.object({
    nextCursor: z.union([z.string(), z.null()]),
    prevCursor: z.union([z.string(), z.null()]),
    hasNextPage: z.boolean(),
    hasPrevPage: z.boolean(),
    limit: z.number().int(),
  }),
});

export const zPostApiV1EventsByEventIdPhotosUploadIntentData = z.object({
  files: z
    .array(
      z.object({
        filename: z.string().min(1).max(255),
        contentType: z.enum(['image/jpeg', 'image/png', 'image/webp', 'image/avif']),
        fileSize: z.number().int().gte(1).lte(26214400),
        checksum: z
          .string()
          .regex(/^[0-9a-f]{64}$/)
          .optional(),
      }),
    )
    .min(1)
    .max(50),
});

export const zPostApiV1EventsByEventIdPhotosUploadIntentParameterEventId = z
  .string()
  .regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * Upload slots, and any duplicates that were skipped.
 */
export const zPostApiV1EventsByEventIdPhotosUploadIntentResponse = z.object({
  uploads: z.array(
    z.object({
      photoId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      filename: z.string(),
      uploadUrl: z.string(),
      storageKey: z.string(),
      expiresAt: z.number().int(),
    }),
  ),
  duplicates: z.array(
    z.object({
      filename: z.string(),
      existingPhotoId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
    }),
  ),
});

export const zPostApiV1EventsByEventIdPhotosConfirmData = z.object({
  items: z
    .array(
      z.object({
        photoId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
        width: z.number().int().gt(0).lte(60000).optional(),
        height: z.number().int().gt(0).lte(60000).optional(),
        takenAt: z.number().int().optional(),
        dominantColor: z
          .string()
          .regex(/^#[0-9a-f]{6}$/)
          .optional(),
      }),
    )
    .min(1)
    .max(50),
});

export const zPostApiV1EventsByEventIdPhotosConfirmParameterEventId = z
  .string()
  .regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * What became ready.
 */
export const zPostApiV1EventsByEventIdPhotosConfirmResponse = z.object({
  confirmed: z.number().int(),
  missing: z.array(z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/)),
});

export const zGetApiV1EventsByEventIdPhotosParameterEventId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

export const zGetApiV1EventsByEventIdPhotosParameterLimit = z.number().int().gte(1).lte(100).default(24);

export const zGetApiV1EventsByEventIdPhotosParameterCursor = z.string().max(512);

export const zGetApiV1EventsByEventIdPhotosParameterSort = z.enum([
  'newest',
  'oldest',
  'filename',
  'size',
  'taken',
]);

export const zGetApiV1EventsByEventIdPhotosParameterSearch = z.string().max(120);

export const zGetApiV1EventsByEventIdPhotosParameterUploaderId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

export const zGetApiV1EventsByEventIdPhotosParameterSelected = z.enum(['true', 'false']);

export const zGetApiV1EventsByEventIdPhotosParameterFrom = z.union([z.number().int(), z.null()]);

export const zGetApiV1EventsByEventIdPhotosParameterTo = z.union([z.number().int(), z.null()]);

/**
 * A page of photos.
 */
export const zGetApiV1EventsByEventIdPhotosResponse = z.object({
  data: z.array(
    z.object({
      id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      eventId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      uploadedBy: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      uploaderName: z.string().optional(),
      filename: z.string(),
      storageKey: z.string(),
      contentType: z.string(),
      fileSize: z.number().int(),
      width: z.union([z.number().int(), z.null()]),
      height: z.union([z.number().int(), z.null()]),
      dominantColor: z.union([z.string(), z.null()]),
      caption: z.union([z.string(), z.null()]),
      takenAt: z.union([z.number().int(), z.null()]),
      status: z.enum(['pending', 'ready', 'failed', 'deleted']),
      isSelected: z.boolean(),
      createdAt: z.number().int(),
    }),
  ),
  pageInfo: z.object({
    nextCursor: z.union([z.string(), z.null()]),
    prevCursor: z.union([z.string(), z.null()]),
    hasNextPage: z.boolean(),
    hasPrevPage: z.boolean(),
    limit: z.number().int(),
  }),
});

export const zPostApiV1EventsByEventIdPhotosSelectData = z.object({
  photoIds: z
    .array(z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/))
    .min(1)
    .max(500),
  selected: z.boolean(),
});

export const zPostApiV1EventsByEventIdPhotosSelectParameterEventId = z
  .string()
  .regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * How many changed.
 */
export const zPostApiV1EventsByEventIdPhotosSelectResponse = z.object({
  updated: z.number().int(),
});

export const zDeleteApiV1PhotosByPhotoIdParameterPhotoId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * Deleted.
 */
export const zDeleteApiV1PhotosByPhotoIdResponse = z.void();

export const zPatchApiV1PhotosByPhotoIdData = z.object({
  caption: z.union([z.string().max(500), z.null()]).optional(),
  isSelected: z.boolean().optional(),
});

export const zPatchApiV1PhotosByPhotoIdParameterPhotoId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * The updated photo.
 */
export const zPatchApiV1PhotosByPhotoIdResponse = z.object({
  id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  eventId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  uploadedBy: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  uploaderName: z.string().optional(),
  filename: z.string(),
  storageKey: z.string(),
  contentType: z.string(),
  fileSize: z.number().int(),
  width: z.union([z.number().int(), z.null()]),
  height: z.union([z.number().int(), z.null()]),
  dominantColor: z.union([z.string(), z.null()]),
  caption: z.union([z.string(), z.null()]),
  takenAt: z.union([z.number().int(), z.null()]),
  status: z.enum(['pending', 'ready', 'failed', 'deleted']),
  isSelected: z.boolean(),
  createdAt: z.number().int(),
});

export const zPostApiV1EventsByEventIdPhotosDeleteData = z.object({
  photoIds: z
    .array(z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/))
    .min(1)
    .max(500),
});

export const zPostApiV1EventsByEventIdPhotosDeleteParameterEventId = z
  .string()
  .regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * Number of newly deleted photos.
 */
export const zPostApiV1EventsByEventIdPhotosDeleteResponse = z.object({
  deleted: z.number().int(),
});

export const zGetApiV1EventsByEventIdGalleriesParameterEventId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

export const zGetApiV1EventsByEventIdGalleriesParameterLimit = z.number().int().gte(1).lte(100).default(24);

export const zGetApiV1EventsByEventIdGalleriesParameterCursor = z.string().max(512);

/**
 * A page of galleries.
 */
export const zGetApiV1EventsByEventIdGalleriesResponse = z.object({
  data: z.array(
    z.object({
      id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      eventId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      slug: z.string(),
      title: z.string(),
      status: z.enum(['draft', 'published', 'unpublished']),
      photoCount: z.number().int(),
      allowDownload: z.boolean(),
      expiresAt: z.union([z.number().int(), z.null()]),
      publishedAt: z.union([z.number().int(), z.null()]),
      viewCount: z.number().int(),
      lastViewedAt: z.union([z.number().int(), z.null()]),
      createdAt: z.number().int(),
    }),
  ),
  pageInfo: z.object({
    nextCursor: z.union([z.string(), z.null()]),
    prevCursor: z.union([z.string(), z.null()]),
    hasNextPage: z.boolean(),
    hasPrevPage: z.boolean(),
    limit: z.number().int(),
  }),
});

export const zPostApiV1EventsByEventIdGalleriesData = z.object({
  title: z.string().min(1).max(140),
  photoIds: z
    .array(z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/))
    .max(2000)
    .optional(),
  useSelected: z.boolean().optional(),
  expiresAt: z.number().int().optional(),
  allowDownload: z.boolean().optional().default(true),
  publish: z.boolean().optional().default(false),
  pin: z
    .string()
    .regex(/^\d{6}$/)
    .optional(),
});

export const zPostApiV1EventsByEventIdGalleriesParameterEventId = z
  .string()
  .regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * Created. The PIN appears here and nowhere else.
 */
export const zPostApiV1EventsByEventIdGalleriesResponse = z.object({
  gallery: z.object({
    id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
    eventId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
    slug: z.string(),
    title: z.string(),
    status: z.enum(['draft', 'published', 'unpublished']),
    photoCount: z.number().int(),
    allowDownload: z.boolean(),
    expiresAt: z.union([z.number().int(), z.null()]),
    publishedAt: z.union([z.number().int(), z.null()]),
    viewCount: z.number().int(),
    lastViewedAt: z.union([z.number().int(), z.null()]),
    createdAt: z.number().int(),
  }),
  url: z.string(),
  pin: z.string(),
});

export const zPostApiV1GalleriesByGalleryIdPublishParameterGalleryId = z
  .string()
  .regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * The updated gallery.
 */
export const zPostApiV1GalleriesByGalleryIdPublishResponse = z.object({
  id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  eventId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  slug: z.string(),
  title: z.string(),
  status: z.enum(['draft', 'published', 'unpublished']),
  photoCount: z.number().int(),
  allowDownload: z.boolean(),
  expiresAt: z.union([z.number().int(), z.null()]),
  publishedAt: z.union([z.number().int(), z.null()]),
  viewCount: z.number().int(),
  lastViewedAt: z.union([z.number().int(), z.null()]),
  createdAt: z.number().int(),
});

export const zPostApiV1GalleriesByGalleryIdUnpublishParameterGalleryId = z
  .string()
  .regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * The updated gallery.
 */
export const zPostApiV1GalleriesByGalleryIdUnpublishResponse = z.object({
  id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  eventId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  slug: z.string(),
  title: z.string(),
  status: z.enum(['draft', 'published', 'unpublished']),
  photoCount: z.number().int(),
  allowDownload: z.boolean(),
  expiresAt: z.union([z.number().int(), z.null()]),
  publishedAt: z.union([z.number().int(), z.null()]),
  viewCount: z.number().int(),
  lastViewedAt: z.union([z.number().int(), z.null()]),
  createdAt: z.number().int(),
});

export const zPostApiV1GalleriesByGalleryIdRotatePinParameterGalleryId = z
  .string()
  .regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * The new PIN. This is the only time it is shown.
 */
export const zPostApiV1GalleriesByGalleryIdRotatePinResponse = z.object({
  pin: z.string(),
});

export const zDeleteApiV1GalleriesByGalleryIdParameterGalleryId = z
  .string()
  .regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * Deleted.
 */
export const zDeleteApiV1GalleriesByGalleryIdResponse = z.void();

export const zPatchApiV1GalleriesByGalleryIdData = z.object({
  title: z.string().min(1).max(140).optional(),
  expiresAt: z.union([z.number().int(), z.null()]).optional(),
  allowDownload: z.boolean().optional(),
  coverPhotoId: z.union([z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/), z.null()]).optional(),
});

export const zPatchApiV1GalleriesByGalleryIdParameterGalleryId = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

/**
 * The updated gallery.
 */
export const zPatchApiV1GalleriesByGalleryIdResponse = z.object({
  id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  eventId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
  slug: z.string(),
  title: z.string(),
  status: z.enum(['draft', 'published', 'unpublished']),
  photoCount: z.number().int(),
  allowDownload: z.boolean(),
  expiresAt: z.union([z.number().int(), z.null()]),
  publishedAt: z.union([z.number().int(), z.null()]),
  viewCount: z.number().int(),
  lastViewedAt: z.union([z.number().int(), z.null()]),
  createdAt: z.number().int(),
});

export const zGetApiV1PublicGalleriesBySlugParameterSlug = z.string().min(16).max(100);

/**
 * Safe metadata for the PIN screen.
 */
export const zGetApiV1PublicGalleriesBySlugResponse = z.object({
  title: z.string(),
  photoCount: z.number().int(),
  coverThumbUrl: z.union([z.string(), z.null()]),
  allowDownload: z.boolean(),
  expiresAt: z.union([z.number().int(), z.null()]),
  unlocked: z.boolean(),
});

export const zPostApiV1PublicGalleriesBySlugUnlockData = z.object({
  pin: z.string().regex(/^\d{6}$/),
});

export const zPostApiV1PublicGalleriesBySlugUnlockParameterSlug = z.string().min(16).max(100);

/**
 * Unlocked. A gallery-specific, path-scoped cookie was set.
 */
export const zPostApiV1PublicGalleriesBySlugUnlockResponse = z.void();

export const zGetApiV1PublicGalleriesBySlugPhotosParameterSlug = z.string();

export const zGetApiV1PublicGalleriesBySlugPhotosParameterLimit = z
  .number()
  .int()
  .gte(1)
  .lte(100)
  .default(24);

export const zGetApiV1PublicGalleriesBySlugPhotosParameterCursor = z.string().max(512);

/**
 * A curated page.
 */
export const zGetApiV1PublicGalleriesBySlugPhotosResponse = z.object({
  data: z.array(
    z.object({
      id: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      eventId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      uploadedBy: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/),
      uploaderName: z.string().optional(),
      filename: z.string(),
      storageKey: z.string(),
      contentType: z.string(),
      fileSize: z.number().int(),
      width: z.union([z.number().int(), z.null()]),
      height: z.union([z.number().int(), z.null()]),
      dominantColor: z.union([z.string(), z.null()]),
      caption: z.union([z.string(), z.null()]),
      takenAt: z.union([z.number().int(), z.null()]),
      status: z.enum(['pending', 'ready', 'failed', 'deleted']),
      isSelected: z.boolean(),
      createdAt: z.number().int(),
    }),
  ),
  pageInfo: z.object({
    nextCursor: z.union([z.string(), z.null()]),
    prevCursor: z.union([z.string(), z.null()]),
    hasNextPage: z.boolean(),
    hasPrevPage: z.boolean(),
    limit: z.number().int(),
  }),
});

export const zPostApiV1PublicGalleriesBySlugLockParameterSlug = z.string();

/**
 * This gallery session ended.
 */
export const zPostApiV1PublicGalleriesBySlugLockResponse = z.void();

/**
 * Alive.
 */
export const zGetHealthResponse = z.object({
  status: z.enum(['ok']),
});

/**
 * Ready.
 */
export const zGetReadyResponse = z.object({
  status: z.enum(['ready']),
  db: z.boolean(),
  bucket: z.boolean(),
});
