// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  postApiV1AuthRegister,
  postApiV1AuthLogin,
  getApiV1AuthMe,
  postApiV1AuthLogout,
  getApiV1AuthSessions,
  deleteApiV1AuthSessionsById,
  postApiV1AuthSessionsRevokeAll,
  getApiV1Events,
  postApiV1Events,
  getApiV1EventsByEventId,
  getApiV1EventsByEventIdStats,
  getApiV1EventsByEventIdMembers,
  postApiV1EventsByEventIdMembers,
  deleteApiV1EventsByEventIdMembersByUserId,
  getApiV1EventsByEventIdAudit,
  postApiV1EventsByEventIdPhotosUploadIntent,
  postApiV1EventsByEventIdPhotosConfirm,
  getApiV1EventsByEventIdPhotos,
  postApiV1EventsByEventIdPhotosSelect,
  deleteApiV1PhotosByPhotoId,
  patchApiV1PhotosByPhotoId,
  postApiV1EventsByEventIdPhotosDelete,
  getApiV1EventsByEventIdGalleries,
  postApiV1EventsByEventIdGalleries,
  postApiV1GalleriesByGalleryIdPublish,
  postApiV1GalleriesByGalleryIdUnpublish,
  postApiV1GalleriesByGalleryIdRotatePin,
  deleteApiV1GalleriesByGalleryId,
  patchApiV1GalleriesByGalleryId,
  getApiV1PublicGalleriesBySlug,
  postApiV1PublicGalleriesBySlugUnlock,
  getApiV1PublicGalleriesBySlugPhotos,
  postApiV1PublicGalleriesBySlugLock,
  getHealth,
  getReady,
} from '../sdk.gen';
import {
  queryOptions,
  type UseMutationOptions,
  infiniteQueryOptions,
  type InfiniteData,
} from '@tanstack/react-query';
import type {
  PostApiV1AuthRegisterData,
  PostApiV1AuthRegisterError,
  PostApiV1AuthRegisterResponse,
  PostApiV1AuthLoginData,
  PostApiV1AuthLoginError,
  PostApiV1AuthLoginResponse,
  GetApiV1AuthMeData,
  PostApiV1AuthLogoutData,
  PostApiV1AuthLogoutError,
  PostApiV1AuthLogoutResponse,
  GetApiV1AuthSessionsData,
  DeleteApiV1AuthSessionsByIdData,
  DeleteApiV1AuthSessionsByIdError,
  DeleteApiV1AuthSessionsByIdResponse,
  PostApiV1AuthSessionsRevokeAllData,
  PostApiV1AuthSessionsRevokeAllError,
  PostApiV1AuthSessionsRevokeAllResponse,
  GetApiV1EventsData,
  GetApiV1EventsError,
  GetApiV1EventsResponse,
  PostApiV1EventsData,
  PostApiV1EventsError,
  PostApiV1EventsResponse,
  GetApiV1EventsByEventIdData,
  GetApiV1EventsByEventIdStatsData,
  GetApiV1EventsByEventIdMembersData,
  GetApiV1EventsByEventIdMembersError,
  GetApiV1EventsByEventIdMembersResponse,
  PostApiV1EventsByEventIdMembersData,
  PostApiV1EventsByEventIdMembersError,
  PostApiV1EventsByEventIdMembersResponse,
  DeleteApiV1EventsByEventIdMembersByUserIdData,
  DeleteApiV1EventsByEventIdMembersByUserIdError,
  DeleteApiV1EventsByEventIdMembersByUserIdResponse,
  GetApiV1EventsByEventIdAuditData,
  GetApiV1EventsByEventIdAuditError,
  GetApiV1EventsByEventIdAuditResponse,
  PostApiV1EventsByEventIdPhotosUploadIntentData,
  PostApiV1EventsByEventIdPhotosUploadIntentError,
  PostApiV1EventsByEventIdPhotosUploadIntentResponse,
  PostApiV1EventsByEventIdPhotosConfirmData,
  PostApiV1EventsByEventIdPhotosConfirmError,
  PostApiV1EventsByEventIdPhotosConfirmResponse,
  GetApiV1EventsByEventIdPhotosData,
  GetApiV1EventsByEventIdPhotosError,
  GetApiV1EventsByEventIdPhotosResponse,
  PostApiV1EventsByEventIdPhotosSelectData,
  PostApiV1EventsByEventIdPhotosSelectError,
  PostApiV1EventsByEventIdPhotosSelectResponse,
  DeleteApiV1PhotosByPhotoIdData,
  DeleteApiV1PhotosByPhotoIdError,
  DeleteApiV1PhotosByPhotoIdResponse,
  PatchApiV1PhotosByPhotoIdData,
  PatchApiV1PhotosByPhotoIdError,
  PatchApiV1PhotosByPhotoIdResponse,
  PostApiV1EventsByEventIdPhotosDeleteData,
  PostApiV1EventsByEventIdPhotosDeleteError,
  PostApiV1EventsByEventIdPhotosDeleteResponse,
  GetApiV1EventsByEventIdGalleriesData,
  GetApiV1EventsByEventIdGalleriesError,
  GetApiV1EventsByEventIdGalleriesResponse,
  PostApiV1EventsByEventIdGalleriesData,
  PostApiV1EventsByEventIdGalleriesError,
  PostApiV1EventsByEventIdGalleriesResponse,
  PostApiV1GalleriesByGalleryIdPublishData,
  PostApiV1GalleriesByGalleryIdPublishError,
  PostApiV1GalleriesByGalleryIdPublishResponse,
  PostApiV1GalleriesByGalleryIdUnpublishData,
  PostApiV1GalleriesByGalleryIdUnpublishError,
  PostApiV1GalleriesByGalleryIdUnpublishResponse,
  PostApiV1GalleriesByGalleryIdRotatePinData,
  PostApiV1GalleriesByGalleryIdRotatePinError,
  PostApiV1GalleriesByGalleryIdRotatePinResponse,
  DeleteApiV1GalleriesByGalleryIdData,
  DeleteApiV1GalleriesByGalleryIdError,
  DeleteApiV1GalleriesByGalleryIdResponse,
  PatchApiV1GalleriesByGalleryIdData,
  PatchApiV1GalleriesByGalleryIdError,
  PatchApiV1GalleriesByGalleryIdResponse,
  GetApiV1PublicGalleriesBySlugData,
  PostApiV1PublicGalleriesBySlugUnlockData,
  PostApiV1PublicGalleriesBySlugUnlockError,
  PostApiV1PublicGalleriesBySlugUnlockResponse,
  GetApiV1PublicGalleriesBySlugPhotosData,
  GetApiV1PublicGalleriesBySlugPhotosError,
  GetApiV1PublicGalleriesBySlugPhotosResponse,
  PostApiV1PublicGalleriesBySlugLockData,
  PostApiV1PublicGalleriesBySlugLockError,
  PostApiV1PublicGalleriesBySlugLockResponse,
  GetHealthData,
  GetReadyData,
} from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const postApiV1AuthRegisterQueryKey = (options: Options<PostApiV1AuthRegisterData>) =>
  createQueryKey('postApiV1AuthRegister', options);

/**
 * Create an account
 * Creates a platform account and signs it in. The first account you create is the Admin/Lead; team members are normally created through an event invite instead.
 */
export const postApiV1AuthRegisterOptions = (options: Options<PostApiV1AuthRegisterData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1AuthRegister({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1AuthRegisterQueryKey(options),
  });
};

/**
 * Create an account
 * Creates a platform account and signs it in. The first account you create is the Admin/Lead; team members are normally created through an event invite instead.
 */
export const postApiV1AuthRegisterMutation = (
  options?: Partial<Options<PostApiV1AuthRegisterData>>,
): UseMutationOptions<
  PostApiV1AuthRegisterResponse,
  PostApiV1AuthRegisterError,
  Options<PostApiV1AuthRegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1AuthRegisterResponse,
    PostApiV1AuthRegisterError,
    Options<PostApiV1AuthRegisterData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1AuthRegister({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiV1AuthLoginQueryKey = (options: Options<PostApiV1AuthLoginData>) =>
  createQueryKey('postApiV1AuthLogin', options);

/**
 * Sign in
 * Sets an httpOnly session cookie and a readable CSRF cookie. There is no bearer token: sessions are server-side rows, so signing out or being removed takes effect on the next request.
 */
export const postApiV1AuthLoginOptions = (options: Options<PostApiV1AuthLoginData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1AuthLogin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1AuthLoginQueryKey(options),
  });
};

/**
 * Sign in
 * Sets an httpOnly session cookie and a readable CSRF cookie. There is no bearer token: sessions are server-side rows, so signing out or being removed takes effect on the next request.
 */
export const postApiV1AuthLoginMutation = (
  options?: Partial<Options<PostApiV1AuthLoginData>>,
): UseMutationOptions<
  PostApiV1AuthLoginResponse,
  PostApiV1AuthLoginError,
  Options<PostApiV1AuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1AuthLoginResponse,
    PostApiV1AuthLoginError,
    Options<PostApiV1AuthLoginData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1AuthLogin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1AuthMeQueryKey = (options?: Options<GetApiV1AuthMeData>) =>
  createQueryKey('getApiV1AuthMe', options);

/**
 * Who am I
 * The frontend calls this once on boot to hydrate its auth store. Never cached.
 */
export const getApiV1AuthMeOptions = (options?: Options<GetApiV1AuthMeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1AuthMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1AuthMeQueryKey(options),
  });
};

export const postApiV1AuthLogoutQueryKey = (options?: Options<PostApiV1AuthLogoutData>) =>
  createQueryKey('postApiV1AuthLogout', options);

/**
 * Sign out
 * Deletes the session row. Not a flag, not a denylist -- the row.
 */
export const postApiV1AuthLogoutOptions = (options?: Options<PostApiV1AuthLogoutData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1AuthLogout({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1AuthLogoutQueryKey(options),
  });
};

/**
 * Sign out
 * Deletes the session row. Not a flag, not a denylist -- the row.
 */
export const postApiV1AuthLogoutMutation = (
  options?: Partial<Options<PostApiV1AuthLogoutData>>,
): UseMutationOptions<
  PostApiV1AuthLogoutResponse,
  PostApiV1AuthLogoutError,
  Options<PostApiV1AuthLogoutData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1AuthLogoutResponse,
    PostApiV1AuthLogoutError,
    Options<PostApiV1AuthLogoutData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1AuthLogout({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1AuthSessionsQueryKey = (options?: Options<GetApiV1AuthSessionsData>) =>
  createQueryKey('getApiV1AuthSessions', options);

/**
 * List active sessions
 * Every device currently signed in as you. "current" marks the one making this request.
 */
export const getApiV1AuthSessionsOptions = (options?: Options<GetApiV1AuthSessionsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1AuthSessions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1AuthSessionsQueryKey(options),
  });
};

/**
 * End one session
 */
export const deleteApiV1AuthSessionsByIdMutation = (
  options?: Partial<Options<DeleteApiV1AuthSessionsByIdData>>,
): UseMutationOptions<
  DeleteApiV1AuthSessionsByIdResponse,
  DeleteApiV1AuthSessionsByIdError,
  Options<DeleteApiV1AuthSessionsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiV1AuthSessionsByIdResponse,
    DeleteApiV1AuthSessionsByIdError,
    Options<DeleteApiV1AuthSessionsByIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteApiV1AuthSessionsById({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiV1AuthSessionsRevokeAllQueryKey = (
  options?: Options<PostApiV1AuthSessionsRevokeAllData>,
) => createQueryKey('postApiV1AuthSessionsRevokeAll', options);

/**
 * Sign out everywhere else
 * Ends every session except the one making this request.
 */
export const postApiV1AuthSessionsRevokeAllOptions = (
  options?: Options<PostApiV1AuthSessionsRevokeAllData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1AuthSessionsRevokeAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1AuthSessionsRevokeAllQueryKey(options),
  });
};

/**
 * Sign out everywhere else
 * Ends every session except the one making this request.
 */
export const postApiV1AuthSessionsRevokeAllMutation = (
  options?: Partial<Options<PostApiV1AuthSessionsRevokeAllData>>,
): UseMutationOptions<
  PostApiV1AuthSessionsRevokeAllResponse,
  PostApiV1AuthSessionsRevokeAllError,
  Options<PostApiV1AuthSessionsRevokeAllData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1AuthSessionsRevokeAllResponse,
    PostApiV1AuthSessionsRevokeAllError,
    Options<PostApiV1AuthSessionsRevokeAllData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1AuthSessionsRevokeAll({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1EventsQueryKey = (options?: Options<GetApiV1EventsData>) =>
  createQueryKey('getApiV1Events', options);

/**
 * List my events
 * Only events you are a member of. Cursor-paginated, newest first.
 */
export const getApiV1EventsOptions = (options?: Options<GetApiV1EventsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1Events({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1EventsQueryKey(options),
  });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {
    ...queryKey[0],
  };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getApiV1EventsInfiniteQueryKey = (
  options?: Options<GetApiV1EventsData>,
): QueryKey<Options<GetApiV1EventsData>> => createQueryKey('getApiV1Events', options, true);

/**
 * List my events
 * Only events you are a member of. Cursor-paginated, newest first.
 */
export const getApiV1EventsInfiniteOptions = (options?: Options<GetApiV1EventsData>) => {
  return infiniteQueryOptions<
    GetApiV1EventsResponse,
    GetApiV1EventsError,
    InfiniteData<GetApiV1EventsResponse>,
    QueryKey<Options<GetApiV1EventsData>>,
    string | Pick<QueryKey<Options<GetApiV1EventsData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiV1EventsData>>[0], 'body' | 'headers' | 'path' | 'query'> =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1Events({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiV1EventsInfiniteQueryKey(options),
    },
  );
};

export const postApiV1EventsQueryKey = (options: Options<PostApiV1EventsData>) =>
  createQueryKey('postApiV1Events', options);

/**
 * Create an event
 * The creator becomes its admin. Only platform admins can create events.
 */
export const postApiV1EventsOptions = (options: Options<PostApiV1EventsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1Events({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1EventsQueryKey(options),
  });
};

/**
 * Create an event
 * The creator becomes its admin. Only platform admins can create events.
 */
export const postApiV1EventsMutation = (
  options?: Partial<Options<PostApiV1EventsData>>,
): UseMutationOptions<PostApiV1EventsResponse, PostApiV1EventsError, Options<PostApiV1EventsData>> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1EventsResponse,
    PostApiV1EventsError,
    Options<PostApiV1EventsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1Events({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1EventsByEventIdQueryKey = (options: Options<GetApiV1EventsByEventIdData>) =>
  createQueryKey('getApiV1EventsByEventId', options);

/**
 * Get one event
 * A non-member gets 404, not 403: confirming an event exists is itself a leak.
 */
export const getApiV1EventsByEventIdOptions = (options: Options<GetApiV1EventsByEventIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1EventsByEventId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1EventsByEventIdQueryKey(options),
  });
};

export const getApiV1EventsByEventIdStatsQueryKey = (options: Options<GetApiV1EventsByEventIdStatsData>) =>
  createQueryKey('getApiV1EventsByEventIdStats', options);

/**
 * Event totals
 * Counts live here, deliberately away from the paginated list endpoints, so a page fetch never pays for a COUNT(*) over 1,250 rows.
 */
export const getApiV1EventsByEventIdStatsOptions = (options: Options<GetApiV1EventsByEventIdStatsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1EventsByEventIdStats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1EventsByEventIdStatsQueryKey(options),
  });
};

export const getApiV1EventsByEventIdMembersQueryKey = (
  options: Options<GetApiV1EventsByEventIdMembersData>,
) => createQueryKey('getApiV1EventsByEventIdMembers', options);

/**
 * List team members
 */
export const getApiV1EventsByEventIdMembersOptions = (
  options: Options<GetApiV1EventsByEventIdMembersData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1EventsByEventIdMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1EventsByEventIdMembersQueryKey(options),
  });
};

export const getApiV1EventsByEventIdMembersInfiniteQueryKey = (
  options: Options<GetApiV1EventsByEventIdMembersData>,
): QueryKey<Options<GetApiV1EventsByEventIdMembersData>> =>
  createQueryKey('getApiV1EventsByEventIdMembers', options, true);

/**
 * List team members
 */
export const getApiV1EventsByEventIdMembersInfiniteOptions = (
  options: Options<GetApiV1EventsByEventIdMembersData>,
) => {
  return infiniteQueryOptions<
    GetApiV1EventsByEventIdMembersResponse,
    GetApiV1EventsByEventIdMembersError,
    InfiniteData<GetApiV1EventsByEventIdMembersResponse>,
    QueryKey<Options<GetApiV1EventsByEventIdMembersData>>,
    | string
    | Pick<QueryKey<Options<GetApiV1EventsByEventIdMembersData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiV1EventsByEventIdMembersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1EventsByEventIdMembers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiV1EventsByEventIdMembersInfiniteQueryKey(options),
    },
  );
};

export const postApiV1EventsByEventIdMembersQueryKey = (
  options: Options<PostApiV1EventsByEventIdMembersData>,
) => createQueryKey('postApiV1EventsByEventIdMembers', options);

/**
 * Add a team member
 * Creates the account if the email is new and returns a one-time password for the demo. A real deployment would email an invite link instead; see the README.
 */
export const postApiV1EventsByEventIdMembersOptions = (
  options: Options<PostApiV1EventsByEventIdMembersData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1EventsByEventIdMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1EventsByEventIdMembersQueryKey(options),
  });
};

/**
 * Add a team member
 * Creates the account if the email is new and returns a one-time password for the demo. A real deployment would email an invite link instead; see the README.
 */
export const postApiV1EventsByEventIdMembersMutation = (
  options?: Partial<Options<PostApiV1EventsByEventIdMembersData>>,
): UseMutationOptions<
  PostApiV1EventsByEventIdMembersResponse,
  PostApiV1EventsByEventIdMembersError,
  Options<PostApiV1EventsByEventIdMembersData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1EventsByEventIdMembersResponse,
    PostApiV1EventsByEventIdMembersError,
    Options<PostApiV1EventsByEventIdMembersData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1EventsByEventIdMembers({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove a team member
 * Takes effect on their next request -- sessions are rows, so there is no token left to expire. The last admin cannot be removed.
 */
export const deleteApiV1EventsByEventIdMembersByUserIdMutation = (
  options?: Partial<Options<DeleteApiV1EventsByEventIdMembersByUserIdData>>,
): UseMutationOptions<
  DeleteApiV1EventsByEventIdMembersByUserIdResponse,
  DeleteApiV1EventsByEventIdMembersByUserIdError,
  Options<DeleteApiV1EventsByEventIdMembersByUserIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiV1EventsByEventIdMembersByUserIdResponse,
    DeleteApiV1EventsByEventIdMembersByUserIdError,
    Options<DeleteApiV1EventsByEventIdMembersByUserIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteApiV1EventsByEventIdMembersByUserId({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1EventsByEventIdAuditQueryKey = (options: Options<GetApiV1EventsByEventIdAuditData>) =>
  createQueryKey('getApiV1EventsByEventIdAudit', options);

/**
 * Audit log
 * Who did what on this event. Cursor-paginated, newest first.
 */
export const getApiV1EventsByEventIdAuditOptions = (options: Options<GetApiV1EventsByEventIdAuditData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1EventsByEventIdAudit({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1EventsByEventIdAuditQueryKey(options),
  });
};

export const getApiV1EventsByEventIdAuditInfiniteQueryKey = (
  options: Options<GetApiV1EventsByEventIdAuditData>,
): QueryKey<Options<GetApiV1EventsByEventIdAuditData>> =>
  createQueryKey('getApiV1EventsByEventIdAudit', options, true);

/**
 * Audit log
 * Who did what on this event. Cursor-paginated, newest first.
 */
export const getApiV1EventsByEventIdAuditInfiniteOptions = (
  options: Options<GetApiV1EventsByEventIdAuditData>,
) => {
  return infiniteQueryOptions<
    GetApiV1EventsByEventIdAuditResponse,
    GetApiV1EventsByEventIdAuditError,
    InfiniteData<GetApiV1EventsByEventIdAuditResponse>,
    QueryKey<Options<GetApiV1EventsByEventIdAuditData>>,
    | string
    | Pick<QueryKey<Options<GetApiV1EventsByEventIdAuditData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiV1EventsByEventIdAuditData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1EventsByEventIdAudit({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiV1EventsByEventIdAuditInfiniteQueryKey(options),
    },
  );
};

export const postApiV1EventsByEventIdPhotosUploadIntentQueryKey = (
  options: Options<PostApiV1EventsByEventIdPhotosUploadIntentData>,
) => createQueryKey('postApiV1EventsByEventIdPhotosUploadIntent', options);

/**
 * Reserve upload slots
 * Validates the batch, reserves `pending` rows, and returns signed Supabase Storage PUT URLs. Bytes go straight to Supabase Storage and never pass through the API. Send the whole batch in one call, not one call per file. Files whose checksum already exists in this event come back under `duplicates` with no upload slot.
 */
export const postApiV1EventsByEventIdPhotosUploadIntentOptions = (
  options: Options<PostApiV1EventsByEventIdPhotosUploadIntentData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1EventsByEventIdPhotosUploadIntent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1EventsByEventIdPhotosUploadIntentQueryKey(options),
  });
};

/**
 * Reserve upload slots
 * Validates the batch, reserves `pending` rows, and returns signed Supabase Storage PUT URLs. Bytes go straight to Supabase Storage and never pass through the API. Send the whole batch in one call, not one call per file. Files whose checksum already exists in this event come back under `duplicates` with no upload slot.
 */
export const postApiV1EventsByEventIdPhotosUploadIntentMutation = (
  options?: Partial<Options<PostApiV1EventsByEventIdPhotosUploadIntentData>>,
): UseMutationOptions<
  PostApiV1EventsByEventIdPhotosUploadIntentResponse,
  PostApiV1EventsByEventIdPhotosUploadIntentError,
  Options<PostApiV1EventsByEventIdPhotosUploadIntentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1EventsByEventIdPhotosUploadIntentResponse,
    PostApiV1EventsByEventIdPhotosUploadIntentError,
    Options<PostApiV1EventsByEventIdPhotosUploadIntentData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1EventsByEventIdPhotosUploadIntent({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiV1EventsByEventIdPhotosConfirmQueryKey = (
  options: Options<PostApiV1EventsByEventIdPhotosConfirmData>,
) => createQueryKey('postApiV1EventsByEventIdPhotosConfirm', options);

/**
 * Confirm uploaded files
 * Flips `pending` rows to `ready` and records dimensions and EXIF. Idempotent: a retried confirm after a flaky response changes nothing.
 */
export const postApiV1EventsByEventIdPhotosConfirmOptions = (
  options: Options<PostApiV1EventsByEventIdPhotosConfirmData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1EventsByEventIdPhotosConfirm({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1EventsByEventIdPhotosConfirmQueryKey(options),
  });
};

/**
 * Confirm uploaded files
 * Flips `pending` rows to `ready` and records dimensions and EXIF. Idempotent: a retried confirm after a flaky response changes nothing.
 */
export const postApiV1EventsByEventIdPhotosConfirmMutation = (
  options?: Partial<Options<PostApiV1EventsByEventIdPhotosConfirmData>>,
): UseMutationOptions<
  PostApiV1EventsByEventIdPhotosConfirmResponse,
  PostApiV1EventsByEventIdPhotosConfirmError,
  Options<PostApiV1EventsByEventIdPhotosConfirmData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1EventsByEventIdPhotosConfirmResponse,
    PostApiV1EventsByEventIdPhotosConfirmError,
    Options<PostApiV1EventsByEventIdPhotosConfirmData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1EventsByEventIdPhotosConfirm({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1EventsByEventIdPhotosQueryKey = (options: Options<GetApiV1EventsByEventIdPhotosData>) =>
  createQueryKey('getApiV1EventsByEventIdPhotos', options);

/**
 * List photos in an event
 * Cursor-paginated. Pass `pageInfo.nextCursor` from the previous response as `cursor`. Cursors are signed and bound to the `sort` that minted them, so changing `sort` mid-walk returns 400 rather than a quietly wrong page. Filters compose into the keyset query without breaking the cursor.
 */
export const getApiV1EventsByEventIdPhotosOptions = (options: Options<GetApiV1EventsByEventIdPhotosData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1EventsByEventIdPhotos({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1EventsByEventIdPhotosQueryKey(options),
  });
};

export const getApiV1EventsByEventIdPhotosInfiniteQueryKey = (
  options: Options<GetApiV1EventsByEventIdPhotosData>,
): QueryKey<Options<GetApiV1EventsByEventIdPhotosData>> =>
  createQueryKey('getApiV1EventsByEventIdPhotos', options, true);

/**
 * List photos in an event
 * Cursor-paginated. Pass `pageInfo.nextCursor` from the previous response as `cursor`. Cursors are signed and bound to the `sort` that minted them, so changing `sort` mid-walk returns 400 rather than a quietly wrong page. Filters compose into the keyset query without breaking the cursor.
 */
export const getApiV1EventsByEventIdPhotosInfiniteOptions = (
  options: Options<GetApiV1EventsByEventIdPhotosData>,
) => {
  return infiniteQueryOptions<
    GetApiV1EventsByEventIdPhotosResponse,
    GetApiV1EventsByEventIdPhotosError,
    InfiniteData<GetApiV1EventsByEventIdPhotosResponse>,
    QueryKey<Options<GetApiV1EventsByEventIdPhotosData>>,
    | string
    | Pick<QueryKey<Options<GetApiV1EventsByEventIdPhotosData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiV1EventsByEventIdPhotosData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1EventsByEventIdPhotos({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiV1EventsByEventIdPhotosInfiniteQueryKey(options),
    },
  );
};

export const postApiV1EventsByEventIdPhotosSelectQueryKey = (
  options: Options<PostApiV1EventsByEventIdPhotosSelectData>,
) => createQueryKey('postApiV1EventsByEventIdPhotosSelect', options);

/**
 * Select or deselect photos in bulk
 * Curation is admin-only. Up to 500 ids per call.
 */
export const postApiV1EventsByEventIdPhotosSelectOptions = (
  options: Options<PostApiV1EventsByEventIdPhotosSelectData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1EventsByEventIdPhotosSelect({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1EventsByEventIdPhotosSelectQueryKey(options),
  });
};

/**
 * Select or deselect photos in bulk
 * Curation is admin-only. Up to 500 ids per call.
 */
export const postApiV1EventsByEventIdPhotosSelectMutation = (
  options?: Partial<Options<PostApiV1EventsByEventIdPhotosSelectData>>,
): UseMutationOptions<
  PostApiV1EventsByEventIdPhotosSelectResponse,
  PostApiV1EventsByEventIdPhotosSelectError,
  Options<PostApiV1EventsByEventIdPhotosSelectData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1EventsByEventIdPhotosSelectResponse,
    PostApiV1EventsByEventIdPhotosSelectError,
    Options<PostApiV1EventsByEventIdPhotosSelectData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1EventsByEventIdPhotosSelect({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a photo
 * Removes a photo from event lists and galleries. Originals remain private in storage. The event lead can delete anything; an uploader can delete their own upload within 15 minutes of uploading it.
 */
export const deleteApiV1PhotosByPhotoIdMutation = (
  options?: Partial<Options<DeleteApiV1PhotosByPhotoIdData>>,
): UseMutationOptions<
  DeleteApiV1PhotosByPhotoIdResponse,
  DeleteApiV1PhotosByPhotoIdError,
  Options<DeleteApiV1PhotosByPhotoIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiV1PhotosByPhotoIdResponse,
    DeleteApiV1PhotosByPhotoIdError,
    Options<DeleteApiV1PhotosByPhotoIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteApiV1PhotosByPhotoId({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Edit one photo
 * The event lead can caption and select. An uploader can caption their own photo but never select it, because selection is a publishing decision.
 */
export const patchApiV1PhotosByPhotoIdMutation = (
  options?: Partial<Options<PatchApiV1PhotosByPhotoIdData>>,
): UseMutationOptions<
  PatchApiV1PhotosByPhotoIdResponse,
  PatchApiV1PhotosByPhotoIdError,
  Options<PatchApiV1PhotosByPhotoIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchApiV1PhotosByPhotoIdResponse,
    PatchApiV1PhotosByPhotoIdError,
    Options<PatchApiV1PhotosByPhotoIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchApiV1PhotosByPhotoId({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiV1EventsByEventIdPhotosDeleteQueryKey = (
  options: Options<PostApiV1EventsByEventIdPhotosDeleteData>,
) => createQueryKey('postApiV1EventsByEventIdPhotosDelete', options);

/**
 * Delete multiple photos
 * Deletes up to 500 photos atomically. Leads may delete event photos; members may delete their own uploads within 15 minutes. Any missing or forbidden photo rejects the entire batch. Originals remain private in storage.
 */
export const postApiV1EventsByEventIdPhotosDeleteOptions = (
  options: Options<PostApiV1EventsByEventIdPhotosDeleteData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1EventsByEventIdPhotosDelete({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1EventsByEventIdPhotosDeleteQueryKey(options),
  });
};

/**
 * Delete multiple photos
 * Deletes up to 500 photos atomically. Leads may delete event photos; members may delete their own uploads within 15 minutes. Any missing or forbidden photo rejects the entire batch. Originals remain private in storage.
 */
export const postApiV1EventsByEventIdPhotosDeleteMutation = (
  options?: Partial<Options<PostApiV1EventsByEventIdPhotosDeleteData>>,
): UseMutationOptions<
  PostApiV1EventsByEventIdPhotosDeleteResponse,
  PostApiV1EventsByEventIdPhotosDeleteError,
  Options<PostApiV1EventsByEventIdPhotosDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1EventsByEventIdPhotosDeleteResponse,
    PostApiV1EventsByEventIdPhotosDeleteError,
    Options<PostApiV1EventsByEventIdPhotosDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1EventsByEventIdPhotosDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1EventsByEventIdGalleriesQueryKey = (
  options: Options<GetApiV1EventsByEventIdGalleriesData>,
) => createQueryKey('getApiV1EventsByEventIdGalleries', options);

/**
 * List galleries for an event
 */
export const getApiV1EventsByEventIdGalleriesOptions = (
  options: Options<GetApiV1EventsByEventIdGalleriesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1EventsByEventIdGalleries({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1EventsByEventIdGalleriesQueryKey(options),
  });
};

export const getApiV1EventsByEventIdGalleriesInfiniteQueryKey = (
  options: Options<GetApiV1EventsByEventIdGalleriesData>,
): QueryKey<Options<GetApiV1EventsByEventIdGalleriesData>> =>
  createQueryKey('getApiV1EventsByEventIdGalleries', options, true);

/**
 * List galleries for an event
 */
export const getApiV1EventsByEventIdGalleriesInfiniteOptions = (
  options: Options<GetApiV1EventsByEventIdGalleriesData>,
) => {
  return infiniteQueryOptions<
    GetApiV1EventsByEventIdGalleriesResponse,
    GetApiV1EventsByEventIdGalleriesError,
    InfiniteData<GetApiV1EventsByEventIdGalleriesResponse>,
    QueryKey<Options<GetApiV1EventsByEventIdGalleriesData>>,
    | string
    | Pick<QueryKey<Options<GetApiV1EventsByEventIdGalleriesData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiV1EventsByEventIdGalleriesData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1EventsByEventIdGalleries({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiV1EventsByEventIdGalleriesInfiniteQueryKey(options),
    },
  );
};

export const postApiV1EventsByEventIdGalleriesQueryKey = (
  options: Options<PostApiV1EventsByEventIdGalleriesData>,
) => createQueryKey('postApiV1EventsByEventIdGalleries', options);

/**
 * Create a gallery
 * Snapshots the chosen photos into the gallery and mints a URL and a 6-digit PIN. **The PIN is returned exactly once and is never readable again** -- store it or rotate it. The snapshot is deliberate: deselecting a photo afterwards does not change what the client already bookmarked.
 */
export const postApiV1EventsByEventIdGalleriesOptions = (
  options: Options<PostApiV1EventsByEventIdGalleriesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1EventsByEventIdGalleries({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1EventsByEventIdGalleriesQueryKey(options),
  });
};

/**
 * Create a gallery
 * Snapshots the chosen photos into the gallery and mints a URL and a 6-digit PIN. **The PIN is returned exactly once and is never readable again** -- store it or rotate it. The snapshot is deliberate: deselecting a photo afterwards does not change what the client already bookmarked.
 */
export const postApiV1EventsByEventIdGalleriesMutation = (
  options?: Partial<Options<PostApiV1EventsByEventIdGalleriesData>>,
): UseMutationOptions<
  PostApiV1EventsByEventIdGalleriesResponse,
  PostApiV1EventsByEventIdGalleriesError,
  Options<PostApiV1EventsByEventIdGalleriesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1EventsByEventIdGalleriesResponse,
    PostApiV1EventsByEventIdGalleriesError,
    Options<PostApiV1EventsByEventIdGalleriesData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1EventsByEventIdGalleries({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiV1GalleriesByGalleryIdPublishQueryKey = (
  options: Options<PostApiV1GalleriesByGalleryIdPublishData>,
) => createQueryKey('postApiV1GalleriesByGalleryIdPublish', options);

/**
 * Publish a gallery
 * Makes the link work. Team members cannot do this.
 */
export const postApiV1GalleriesByGalleryIdPublishOptions = (
  options: Options<PostApiV1GalleriesByGalleryIdPublishData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1GalleriesByGalleryIdPublish({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1GalleriesByGalleryIdPublishQueryKey(options),
  });
};

/**
 * Publish a gallery
 * Makes the link work. Team members cannot do this.
 */
export const postApiV1GalleriesByGalleryIdPublishMutation = (
  options?: Partial<Options<PostApiV1GalleriesByGalleryIdPublishData>>,
): UseMutationOptions<
  PostApiV1GalleriesByGalleryIdPublishResponse,
  PostApiV1GalleriesByGalleryIdPublishError,
  Options<PostApiV1GalleriesByGalleryIdPublishData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1GalleriesByGalleryIdPublishResponse,
    PostApiV1GalleriesByGalleryIdPublishError,
    Options<PostApiV1GalleriesByGalleryIdPublishData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1GalleriesByGalleryIdPublish({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiV1GalleriesByGalleryIdUnpublishQueryKey = (
  options: Options<PostApiV1GalleriesByGalleryIdUnpublishData>,
) => createQueryKey('postApiV1GalleriesByGalleryIdUnpublish', options);

/**
 * Unpublish a gallery
 * Takes the link offline and ends every customer session already inside it.
 */
export const postApiV1GalleriesByGalleryIdUnpublishOptions = (
  options: Options<PostApiV1GalleriesByGalleryIdUnpublishData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1GalleriesByGalleryIdUnpublish({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1GalleriesByGalleryIdUnpublishQueryKey(options),
  });
};

/**
 * Unpublish a gallery
 * Takes the link offline and ends every customer session already inside it.
 */
export const postApiV1GalleriesByGalleryIdUnpublishMutation = (
  options?: Partial<Options<PostApiV1GalleriesByGalleryIdUnpublishData>>,
): UseMutationOptions<
  PostApiV1GalleriesByGalleryIdUnpublishResponse,
  PostApiV1GalleriesByGalleryIdUnpublishError,
  Options<PostApiV1GalleriesByGalleryIdUnpublishData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1GalleriesByGalleryIdUnpublishResponse,
    PostApiV1GalleriesByGalleryIdUnpublishError,
    Options<PostApiV1GalleriesByGalleryIdUnpublishData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1GalleriesByGalleryIdUnpublish({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiV1GalleriesByGalleryIdRotatePinQueryKey = (
  options: Options<PostApiV1GalleriesByGalleryIdRotatePinData>,
) => createQueryKey('postApiV1GalleriesByGalleryIdRotatePin', options);

/**
 * Issue a new PIN
 * Mints a new PIN and **ends every customer session already inside the gallery**, so the old PIN and anyone using it are locked out immediately. Shown once.
 */
export const postApiV1GalleriesByGalleryIdRotatePinOptions = (
  options: Options<PostApiV1GalleriesByGalleryIdRotatePinData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1GalleriesByGalleryIdRotatePin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1GalleriesByGalleryIdRotatePinQueryKey(options),
  });
};

/**
 * Issue a new PIN
 * Mints a new PIN and **ends every customer session already inside the gallery**, so the old PIN and anyone using it are locked out immediately. Shown once.
 */
export const postApiV1GalleriesByGalleryIdRotatePinMutation = (
  options?: Partial<Options<PostApiV1GalleriesByGalleryIdRotatePinData>>,
): UseMutationOptions<
  PostApiV1GalleriesByGalleryIdRotatePinResponse,
  PostApiV1GalleriesByGalleryIdRotatePinError,
  Options<PostApiV1GalleriesByGalleryIdRotatePinData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1GalleriesByGalleryIdRotatePinResponse,
    PostApiV1GalleriesByGalleryIdRotatePinError,
    Options<PostApiV1GalleriesByGalleryIdRotatePinData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1GalleriesByGalleryIdRotatePin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a gallery
 */
export const deleteApiV1GalleriesByGalleryIdMutation = (
  options?: Partial<Options<DeleteApiV1GalleriesByGalleryIdData>>,
): UseMutationOptions<
  DeleteApiV1GalleriesByGalleryIdResponse,
  DeleteApiV1GalleriesByGalleryIdError,
  Options<DeleteApiV1GalleriesByGalleryIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiV1GalleriesByGalleryIdResponse,
    DeleteApiV1GalleriesByGalleryIdError,
    Options<DeleteApiV1GalleriesByGalleryIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteApiV1GalleriesByGalleryId({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Edit a gallery
 */
export const patchApiV1GalleriesByGalleryIdMutation = (
  options?: Partial<Options<PatchApiV1GalleriesByGalleryIdData>>,
): UseMutationOptions<
  PatchApiV1GalleriesByGalleryIdResponse,
  PatchApiV1GalleriesByGalleryIdError,
  Options<PatchApiV1GalleriesByGalleryIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchApiV1GalleriesByGalleryIdResponse,
    PatchApiV1GalleriesByGalleryIdError,
    Options<PatchApiV1GalleriesByGalleryIdData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchApiV1GalleriesByGalleryId({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1PublicGalleriesBySlugQueryKey = (options: Options<GetApiV1PublicGalleriesBySlugData>) =>
  createQueryKey('getApiV1PublicGalleriesBySlug', options);

/**
 * Preview a private gallery
 * Returns display-safe metadata only. Draft and unknown slugs are indistinguishable.
 */
export const getApiV1PublicGalleriesBySlugOptions = (options: Options<GetApiV1PublicGalleriesBySlugData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1PublicGalleriesBySlug({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1PublicGalleriesBySlugQueryKey(options),
  });
};

export const postApiV1PublicGalleriesBySlugUnlockQueryKey = (
  options: Options<PostApiV1PublicGalleriesBySlugUnlockData>,
) => createQueryKey('postApiV1PublicGalleriesBySlugUnlock', options);

/**
 * Unlock with the client PIN
 * Five failed attempts in 15 minutes are allowed; the sixth is rate-limited.
 */
export const postApiV1PublicGalleriesBySlugUnlockOptions = (
  options: Options<PostApiV1PublicGalleriesBySlugUnlockData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1PublicGalleriesBySlugUnlock({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1PublicGalleriesBySlugUnlockQueryKey(options),
  });
};

/**
 * Unlock with the client PIN
 * Five failed attempts in 15 minutes are allowed; the sixth is rate-limited.
 */
export const postApiV1PublicGalleriesBySlugUnlockMutation = (
  options?: Partial<Options<PostApiV1PublicGalleriesBySlugUnlockData>>,
): UseMutationOptions<
  PostApiV1PublicGalleriesBySlugUnlockResponse,
  PostApiV1PublicGalleriesBySlugUnlockError,
  Options<PostApiV1PublicGalleriesBySlugUnlockData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1PublicGalleriesBySlugUnlockResponse,
    PostApiV1PublicGalleriesBySlugUnlockError,
    Options<PostApiV1PublicGalleriesBySlugUnlockData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1PublicGalleriesBySlugUnlock({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1PublicGalleriesBySlugPhotosQueryKey = (
  options: Options<GetApiV1PublicGalleriesBySlugPhotosData>,
) => createQueryKey('getApiV1PublicGalleriesBySlugPhotos', options);

/**
 * Browse the published snapshot
 */
export const getApiV1PublicGalleriesBySlugPhotosOptions = (
  options: Options<GetApiV1PublicGalleriesBySlugPhotosData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1PublicGalleriesBySlugPhotos({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1PublicGalleriesBySlugPhotosQueryKey(options),
  });
};

export const getApiV1PublicGalleriesBySlugPhotosInfiniteQueryKey = (
  options: Options<GetApiV1PublicGalleriesBySlugPhotosData>,
): QueryKey<Options<GetApiV1PublicGalleriesBySlugPhotosData>> =>
  createQueryKey('getApiV1PublicGalleriesBySlugPhotos', options, true);

/**
 * Browse the published snapshot
 */
export const getApiV1PublicGalleriesBySlugPhotosInfiniteOptions = (
  options: Options<GetApiV1PublicGalleriesBySlugPhotosData>,
) => {
  return infiniteQueryOptions<
    GetApiV1PublicGalleriesBySlugPhotosResponse,
    GetApiV1PublicGalleriesBySlugPhotosError,
    InfiniteData<GetApiV1PublicGalleriesBySlugPhotosResponse>,
    QueryKey<Options<GetApiV1PublicGalleriesBySlugPhotosData>>,
    | string
    | Pick<
        QueryKey<Options<GetApiV1PublicGalleriesBySlugPhotosData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiV1PublicGalleriesBySlugPhotosData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1PublicGalleriesBySlugPhotos({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiV1PublicGalleriesBySlugPhotosInfiniteQueryKey(options),
    },
  );
};

export const postApiV1PublicGalleriesBySlugLockQueryKey = (
  options: Options<PostApiV1PublicGalleriesBySlugLockData>,
) => createQueryKey('postApiV1PublicGalleriesBySlugLock', options);

/**
 * Lock this gallery
 */
export const postApiV1PublicGalleriesBySlugLockOptions = (
  options: Options<PostApiV1PublicGalleriesBySlugLockData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiV1PublicGalleriesBySlugLock({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiV1PublicGalleriesBySlugLockQueryKey(options),
  });
};

/**
 * Lock this gallery
 */
export const postApiV1PublicGalleriesBySlugLockMutation = (
  options?: Partial<Options<PostApiV1PublicGalleriesBySlugLockData>>,
): UseMutationOptions<
  PostApiV1PublicGalleriesBySlugLockResponse,
  PostApiV1PublicGalleriesBySlugLockError,
  Options<PostApiV1PublicGalleriesBySlugLockData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1PublicGalleriesBySlugLockResponse,
    PostApiV1PublicGalleriesBySlugLockError,
    Options<PostApiV1PublicGalleriesBySlugLockData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiV1PublicGalleriesBySlugLock({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

/**
 * Liveness
 * The Worker is running. Says nothing about its dependencies.
 */
export const getHealthOptions = (options?: Options<GetHealthData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHealth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHealthQueryKey(options),
  });
};

export const getReadyQueryKey = (options?: Options<GetReadyData>) => createQueryKey('getReady', options);

/**
 * Readiness
 * Supabase Postgres and Storage are both reachable. This is the one to point a monitor at.
 */
export const getReadyOptions = (options?: Options<GetReadyData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getReady({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getReadyQueryKey(options),
  });
};
